*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSFEVA_ASGTNHR.................................*
FORM GET_DATA_ZOSFEVA_ASGTNHR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSFETB_ASGTNHR WHERE
(VIM_WHERETAB) .
    CLEAR ZOSFEVA_ASGTNHR .
ZOSFEVA_ASGTNHR-MANDT =
ZOSFETB_ASGTNHR-MANDT .
ZOSFEVA_ASGTNHR-TAXTYPE =
ZOSFETB_ASGTNHR-TAXTYPE .
ZOSFEVA_ASGTNHR-STCDT =
ZOSFETB_ASGTNHR-STCDT .
<VIM_TOTAL_STRUC> = ZOSFEVA_ASGTNHR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSFEVA_ASGTNHR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSFEVA_ASGTNHR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSFEVA_ASGTNHR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSFETB_ASGTNHR WHERE
  TAXTYPE = ZOSFEVA_ASGTNHR-TAXTYPE .
    IF SY-SUBRC = 0.
    DELETE ZOSFETB_ASGTNHR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSFETB_ASGTNHR WHERE
  TAXTYPE = ZOSFEVA_ASGTNHR-TAXTYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSFETB_ASGTNHR.
    ENDIF.
ZOSFETB_ASGTNHR-MANDT =
ZOSFEVA_ASGTNHR-MANDT .
ZOSFETB_ASGTNHR-TAXTYPE =
ZOSFEVA_ASGTNHR-TAXTYPE .
ZOSFETB_ASGTNHR-STCDT =
ZOSFEVA_ASGTNHR-STCDT .
    IF SY-SUBRC = 0.
    UPDATE ZOSFETB_ASGTNHR .
    ELSE.
    INSERT ZOSFETB_ASGTNHR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSFEVA_ASGTNHR-UPD_FLAG,
STATUS_ZOSFEVA_ASGTNHR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSFEVA_ASGTNHR.
  SELECT SINGLE * FROM ZOSFETB_ASGTNHR WHERE
TAXTYPE = ZOSFEVA_ASGTNHR-TAXTYPE .
ZOSFEVA_ASGTNHR-MANDT =
ZOSFETB_ASGTNHR-MANDT .
ZOSFEVA_ASGTNHR-TAXTYPE =
ZOSFETB_ASGTNHR-TAXTYPE .
ZOSFEVA_ASGTNHR-STCDT =
ZOSFETB_ASGTNHR-STCDT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSFEVA_ASGTNHR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSFEVA_ASGTNHR-TAXTYPE TO
ZOSFETB_ASGTNHR-TAXTYPE .
MOVE ZOSFEVA_ASGTNHR-MANDT TO
ZOSFETB_ASGTNHR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSFETB_ASGTNHR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSFETB_ASGTNHR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSFETB_ASGTNHR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
