*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSFEVA_DOCUINAC................................*
FORM GET_DATA_ZOSFEVA_DOCUINAC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSFETB_DOCUINAC WHERE
(VIM_WHERETAB) .
    CLEAR ZOSFEVA_DOCUINAC .
ZOSFEVA_DOCUINAC-MANDT =
ZOSFETB_DOCUINAC-MANDT .
ZOSFEVA_DOCUINAC-BUKRS =
ZOSFETB_DOCUINAC-BUKRS .
ZOSFEVA_DOCUINAC-ZZT_TIPODOC =
ZOSFETB_DOCUINAC-ZZT_TIPODOC .
ZOSFEVA_DOCUINAC-ZZT_NUMERACION =
ZOSFETB_DOCUINAC-ZZT_NUMERACION .
ZOSFEVA_DOCUINAC-UPDKZ =
ZOSFETB_DOCUINAC-UPDKZ .
<VIM_TOTAL_STRUC> = ZOSFEVA_DOCUINAC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSFEVA_DOCUINAC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSFEVA_DOCUINAC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSFEVA_DOCUINAC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSFETB_DOCUINAC WHERE
  BUKRS = ZOSFEVA_DOCUINAC-BUKRS AND
  ZZT_TIPODOC = ZOSFEVA_DOCUINAC-ZZT_TIPODOC AND
  ZZT_NUMERACION = ZOSFEVA_DOCUINAC-ZZT_NUMERACION .
    IF SY-SUBRC = 0.
    DELETE ZOSFETB_DOCUINAC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSFETB_DOCUINAC WHERE
  BUKRS = ZOSFEVA_DOCUINAC-BUKRS AND
  ZZT_TIPODOC = ZOSFEVA_DOCUINAC-ZZT_TIPODOC AND
  ZZT_NUMERACION = ZOSFEVA_DOCUINAC-ZZT_NUMERACION .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSFETB_DOCUINAC.
    ENDIF.
ZOSFETB_DOCUINAC-MANDT =
ZOSFEVA_DOCUINAC-MANDT .
ZOSFETB_DOCUINAC-BUKRS =
ZOSFEVA_DOCUINAC-BUKRS .
ZOSFETB_DOCUINAC-ZZT_TIPODOC =
ZOSFEVA_DOCUINAC-ZZT_TIPODOC .
ZOSFETB_DOCUINAC-ZZT_NUMERACION =
ZOSFEVA_DOCUINAC-ZZT_NUMERACION .
ZOSFETB_DOCUINAC-UPDKZ =
ZOSFEVA_DOCUINAC-UPDKZ .
    IF SY-SUBRC = 0.
    UPDATE ZOSFETB_DOCUINAC .
    ELSE.
    INSERT ZOSFETB_DOCUINAC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSFEVA_DOCUINAC-UPD_FLAG,
STATUS_ZOSFEVA_DOCUINAC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSFEVA_DOCUINAC.
  SELECT SINGLE * FROM ZOSFETB_DOCUINAC WHERE
BUKRS = ZOSFEVA_DOCUINAC-BUKRS AND
ZZT_TIPODOC = ZOSFEVA_DOCUINAC-ZZT_TIPODOC AND
ZZT_NUMERACION = ZOSFEVA_DOCUINAC-ZZT_NUMERACION .
ZOSFEVA_DOCUINAC-MANDT =
ZOSFETB_DOCUINAC-MANDT .
ZOSFEVA_DOCUINAC-BUKRS =
ZOSFETB_DOCUINAC-BUKRS .
ZOSFEVA_DOCUINAC-ZZT_TIPODOC =
ZOSFETB_DOCUINAC-ZZT_TIPODOC .
ZOSFEVA_DOCUINAC-ZZT_NUMERACION =
ZOSFETB_DOCUINAC-ZZT_NUMERACION .
ZOSFEVA_DOCUINAC-UPDKZ =
ZOSFETB_DOCUINAC-UPDKZ .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSFEVA_DOCUINAC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSFEVA_DOCUINAC-BUKRS TO
ZOSFETB_DOCUINAC-BUKRS .
MOVE ZOSFEVA_DOCUINAC-ZZT_TIPODOC TO
ZOSFETB_DOCUINAC-ZZT_TIPODOC .
MOVE ZOSFEVA_DOCUINAC-ZZT_NUMERACION TO
ZOSFETB_DOCUINAC-ZZT_NUMERACION .
MOVE ZOSFEVA_DOCUINAC-MANDT TO
ZOSFETB_DOCUINAC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSFETB_DOCUINAC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSFETB_DOCUINAC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSFETB_DOCUINAC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
