*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_ENVWSFE...................................*
FORM GET_DATA_ZOSVA_ENVWSFE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_ENVWSFE WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_ENVWSFE .
ZOSVA_ENVWSFE-MANDT =
ZOSTB_ENVWSFE-MANDT .
ZOSVA_ENVWSFE-BUKRS =
ZOSTB_ENVWSFE-BUKRS .
ZOSVA_ENVWSFE-ENVSUN =
ZOSTB_ENVWSFE-ENVSUN .
ZOSVA_ENVWSFE-TPPROC =
ZOSTB_ENVWSFE-TPPROC .
ZOSVA_ENVWSFE-CLASS =
ZOSTB_ENVWSFE-CLASS .
ZOSVA_ENVWSFE-METHOD =
ZOSTB_ENVWSFE-METHOD .
ZOSVA_ENVWSFE-CLASS2 =
ZOSTB_ENVWSFE-CLASS2 .
ZOSVA_ENVWSFE-METHOD2 =
ZOSTB_ENVWSFE-METHOD2 .
<VIM_TOTAL_STRUC> = ZOSVA_ENVWSFE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_ENVWSFE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_ENVWSFE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_ENVWSFE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_ENVWSFE WHERE
  BUKRS = ZOSVA_ENVWSFE-BUKRS AND
  ENVSUN = ZOSVA_ENVWSFE-ENVSUN AND
  TPPROC = ZOSVA_ENVWSFE-TPPROC .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_ENVWSFE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_ENVWSFE WHERE
  BUKRS = ZOSVA_ENVWSFE-BUKRS AND
  ENVSUN = ZOSVA_ENVWSFE-ENVSUN AND
  TPPROC = ZOSVA_ENVWSFE-TPPROC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_ENVWSFE.
    ENDIF.
ZOSTB_ENVWSFE-MANDT =
ZOSVA_ENVWSFE-MANDT .
ZOSTB_ENVWSFE-BUKRS =
ZOSVA_ENVWSFE-BUKRS .
ZOSTB_ENVWSFE-ENVSUN =
ZOSVA_ENVWSFE-ENVSUN .
ZOSTB_ENVWSFE-TPPROC =
ZOSVA_ENVWSFE-TPPROC .
ZOSTB_ENVWSFE-CLASS =
ZOSVA_ENVWSFE-CLASS .
ZOSTB_ENVWSFE-METHOD =
ZOSVA_ENVWSFE-METHOD .
ZOSTB_ENVWSFE-CLASS2 =
ZOSVA_ENVWSFE-CLASS2 .
ZOSTB_ENVWSFE-METHOD2 =
ZOSVA_ENVWSFE-METHOD2 .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_ENVWSFE .
    ELSE.
    INSERT ZOSTB_ENVWSFE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_ENVWSFE-UPD_FLAG,
STATUS_ZOSVA_ENVWSFE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_ENVWSFE.
  SELECT SINGLE * FROM ZOSTB_ENVWSFE WHERE
BUKRS = ZOSVA_ENVWSFE-BUKRS AND
ENVSUN = ZOSVA_ENVWSFE-ENVSUN AND
TPPROC = ZOSVA_ENVWSFE-TPPROC .
ZOSVA_ENVWSFE-MANDT =
ZOSTB_ENVWSFE-MANDT .
ZOSVA_ENVWSFE-BUKRS =
ZOSTB_ENVWSFE-BUKRS .
ZOSVA_ENVWSFE-ENVSUN =
ZOSTB_ENVWSFE-ENVSUN .
ZOSVA_ENVWSFE-TPPROC =
ZOSTB_ENVWSFE-TPPROC .
ZOSVA_ENVWSFE-CLASS =
ZOSTB_ENVWSFE-CLASS .
ZOSVA_ENVWSFE-METHOD =
ZOSTB_ENVWSFE-METHOD .
ZOSVA_ENVWSFE-CLASS2 =
ZOSTB_ENVWSFE-CLASS2 .
ZOSVA_ENVWSFE-METHOD2 =
ZOSTB_ENVWSFE-METHOD2 .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_ENVWSFE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_ENVWSFE-BUKRS TO
ZOSTB_ENVWSFE-BUKRS .
MOVE ZOSVA_ENVWSFE-ENVSUN TO
ZOSTB_ENVWSFE-ENVSUN .
MOVE ZOSVA_ENVWSFE-TPPROC TO
ZOSTB_ENVWSFE-TPPROC .
MOVE ZOSVA_ENVWSFE-MANDT TO
ZOSTB_ENVWSFE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_ENVWSFE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_ENVWSFE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_ENVWSFE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
