*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_CONSEXTSUN................................*
FORM GET_DATA_ZOSVA_CONSEXTSUN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CONSEXTSUN WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CONSEXTSUN .
ZOSVA_CONSEXTSUN-MANDT =
ZOSTB_CONSEXTSUN-MANDT .
ZOSVA_CONSEXTSUN-BUKRS =
ZOSTB_CONSEXTSUN-BUKRS .
ZOSVA_CONSEXTSUN-ZZ_DESCTOXITEHOM =
ZOSTB_CONSEXTSUN-ZZ_DESCTOXITEHOM .
ZOSVA_CONSEXTSUN-ZZ_VERUBL =
ZOSTB_CONSEXTSUN-ZZ_VERUBL .
ZOSVA_CONSEXTSUN-ZZ_VERESTRDOC =
ZOSTB_CONSEXTSUN-ZZ_VERESTRDOC .
ZOSVA_CONSEXTSUN-ZZ_NCOMERCIAL =
ZOSTB_CONSEXTSUN-ZZ_NCOMERCIAL .
ZOSVA_CONSEXTSUN-ZZ_SOCIEDAD =
ZOSTB_CONSEXTSUN-ZZ_SOCIEDAD .
ZOSVA_CONSEXTSUN-ZZ_UBIGEO =
ZOSTB_CONSEXTSUN-ZZ_UBIGEO .
ZOSVA_CONSEXTSUN-ZZ_DIRECCION =
ZOSTB_CONSEXTSUN-ZZ_DIRECCION .
ZOSVA_CONSEXTSUN-ZZ_URBANIZACION =
ZOSTB_CONSEXTSUN-ZZ_URBANIZACION .
ZOSVA_CONSEXTSUN-ZZ_PROVINCIA =
ZOSTB_CONSEXTSUN-ZZ_PROVINCIA .
ZOSVA_CONSEXTSUN-ZZ_DEPARTAMENTO =
ZOSTB_CONSEXTSUN-ZZ_DEPARTAMENTO .
ZOSVA_CONSEXTSUN-ZZ_DISTRITO =
ZOSTB_CONSEXTSUN-ZZ_DISTRITO .
ZOSVA_CONSEXTSUN-ZZ_PAIS =
ZOSTB_CONSEXTSUN-ZZ_PAIS .
ZOSVA_CONSEXTSUN-ZZ_USUARIO_WEB =
ZOSTB_CONSEXTSUN-ZZ_USUARIO_WEB .
ZOSVA_CONSEXTSUN-ZZ_PASS_WEB =
ZOSTB_CONSEXTSUN-ZZ_PASS_WEB .
ZOSVA_CONSEXTSUN-ZZ_ESTAREGDOC =
ZOSTB_CONSEXTSUN-ZZ_ESTAREGDOC .
ZOSVA_CONSEXTSUN-ZZ_PROXY_NAME =
ZOSTB_CONSEXTSUN-ZZ_PROXY_NAME .
ZOSVA_CONSEXTSUN-ZZ_FACTURA =
ZOSTB_CONSEXTSUN-ZZ_FACTURA .
ZOSVA_CONSEXTSUN-ZZ_BOLETA =
ZOSTB_CONSEXTSUN-ZZ_BOLETA .
ZOSVA_CONSEXTSUN-ZZ_TDOCFACTURA =
ZOSTB_CONSEXTSUN-ZZ_TDOCFACTURA .
ZOSVA_CONSEXTSUN-ZZ_TDOCBOLETA =
ZOSTB_CONSEXTSUN-ZZ_TDOCBOLETA .
ZOSVA_CONSEXTSUN-ZZ_TDOCNOTACRE =
ZOSTB_CONSEXTSUN-ZZ_TDOCNOTACRE .
ZOSVA_CONSEXTSUN-ZZ_TDOCNOTADEB =
ZOSTB_CONSEXTSUN-ZZ_TDOCNOTADEB .
ZOSVA_CONSEXTSUN-ZZ_STATUS_CDR =
ZOSTB_CONSEXTSUN-ZZ_STATUS_CDR .
ZOSVA_CONSEXTSUN-ZZ_RESOL =
ZOSTB_CONSEXTSUN-ZZ_RESOL .
ZOSVA_CONSEXTSUN-ZZ_TDIDBAJ =
ZOSTB_CONSEXTSUN-ZZ_TDIDBAJ .
ZOSVA_CONSEXTSUN-ZZ_PARAMRUC =
ZOSTB_CONSEXTSUN-ZZ_PARAMRUC .
<VIM_TOTAL_STRUC> = ZOSVA_CONSEXTSUN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CONSEXTSUN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CONSEXTSUN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CONSEXTSUN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CONSEXTSUN WHERE
  BUKRS = ZOSVA_CONSEXTSUN-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CONSEXTSUN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CONSEXTSUN WHERE
  BUKRS = ZOSVA_CONSEXTSUN-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CONSEXTSUN.
    ENDIF.
ZOSTB_CONSEXTSUN-MANDT =
ZOSVA_CONSEXTSUN-MANDT .
ZOSTB_CONSEXTSUN-BUKRS =
ZOSVA_CONSEXTSUN-BUKRS .
ZOSTB_CONSEXTSUN-ZZ_DESCTOXITEHOM =
ZOSVA_CONSEXTSUN-ZZ_DESCTOXITEHOM .
ZOSTB_CONSEXTSUN-ZZ_VERUBL =
ZOSVA_CONSEXTSUN-ZZ_VERUBL .
ZOSTB_CONSEXTSUN-ZZ_VERESTRDOC =
ZOSVA_CONSEXTSUN-ZZ_VERESTRDOC .
ZOSTB_CONSEXTSUN-ZZ_NCOMERCIAL =
ZOSVA_CONSEXTSUN-ZZ_NCOMERCIAL .
ZOSTB_CONSEXTSUN-ZZ_SOCIEDAD =
ZOSVA_CONSEXTSUN-ZZ_SOCIEDAD .
ZOSTB_CONSEXTSUN-ZZ_UBIGEO =
ZOSVA_CONSEXTSUN-ZZ_UBIGEO .
ZOSTB_CONSEXTSUN-ZZ_DIRECCION =
ZOSVA_CONSEXTSUN-ZZ_DIRECCION .
ZOSTB_CONSEXTSUN-ZZ_URBANIZACION =
ZOSVA_CONSEXTSUN-ZZ_URBANIZACION .
ZOSTB_CONSEXTSUN-ZZ_PROVINCIA =
ZOSVA_CONSEXTSUN-ZZ_PROVINCIA .
ZOSTB_CONSEXTSUN-ZZ_DEPARTAMENTO =
ZOSVA_CONSEXTSUN-ZZ_DEPARTAMENTO .
ZOSTB_CONSEXTSUN-ZZ_DISTRITO =
ZOSVA_CONSEXTSUN-ZZ_DISTRITO .
ZOSTB_CONSEXTSUN-ZZ_PAIS =
ZOSVA_CONSEXTSUN-ZZ_PAIS .
ZOSTB_CONSEXTSUN-ZZ_USUARIO_WEB =
ZOSVA_CONSEXTSUN-ZZ_USUARIO_WEB .
ZOSTB_CONSEXTSUN-ZZ_PASS_WEB =
ZOSVA_CONSEXTSUN-ZZ_PASS_WEB .
ZOSTB_CONSEXTSUN-ZZ_ESTAREGDOC =
ZOSVA_CONSEXTSUN-ZZ_ESTAREGDOC .
ZOSTB_CONSEXTSUN-ZZ_PROXY_NAME =
ZOSVA_CONSEXTSUN-ZZ_PROXY_NAME .
ZOSTB_CONSEXTSUN-ZZ_FACTURA =
ZOSVA_CONSEXTSUN-ZZ_FACTURA .
ZOSTB_CONSEXTSUN-ZZ_BOLETA =
ZOSVA_CONSEXTSUN-ZZ_BOLETA .
ZOSTB_CONSEXTSUN-ZZ_TDOCFACTURA =
ZOSVA_CONSEXTSUN-ZZ_TDOCFACTURA .
ZOSTB_CONSEXTSUN-ZZ_TDOCBOLETA =
ZOSVA_CONSEXTSUN-ZZ_TDOCBOLETA .
ZOSTB_CONSEXTSUN-ZZ_TDOCNOTACRE =
ZOSVA_CONSEXTSUN-ZZ_TDOCNOTACRE .
ZOSTB_CONSEXTSUN-ZZ_TDOCNOTADEB =
ZOSVA_CONSEXTSUN-ZZ_TDOCNOTADEB .
ZOSTB_CONSEXTSUN-ZZ_STATUS_CDR =
ZOSVA_CONSEXTSUN-ZZ_STATUS_CDR .
ZOSTB_CONSEXTSUN-ZZ_RESOL =
ZOSVA_CONSEXTSUN-ZZ_RESOL .
ZOSTB_CONSEXTSUN-ZZ_TDIDBAJ =
ZOSVA_CONSEXTSUN-ZZ_TDIDBAJ .
ZOSTB_CONSEXTSUN-ZZ_PARAMRUC =
ZOSVA_CONSEXTSUN-ZZ_PARAMRUC .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CONSEXTSUN .
    ELSE.
    INSERT ZOSTB_CONSEXTSUN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CONSEXTSUN-UPD_FLAG,
STATUS_ZOSVA_CONSEXTSUN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CONSEXTSUN.
  SELECT SINGLE * FROM ZOSTB_CONSEXTSUN WHERE
BUKRS = ZOSVA_CONSEXTSUN-BUKRS .
ZOSVA_CONSEXTSUN-MANDT =
ZOSTB_CONSEXTSUN-MANDT .
ZOSVA_CONSEXTSUN-BUKRS =
ZOSTB_CONSEXTSUN-BUKRS .
ZOSVA_CONSEXTSUN-ZZ_DESCTOXITEHOM =
ZOSTB_CONSEXTSUN-ZZ_DESCTOXITEHOM .
ZOSVA_CONSEXTSUN-ZZ_VERUBL =
ZOSTB_CONSEXTSUN-ZZ_VERUBL .
ZOSVA_CONSEXTSUN-ZZ_VERESTRDOC =
ZOSTB_CONSEXTSUN-ZZ_VERESTRDOC .
ZOSVA_CONSEXTSUN-ZZ_NCOMERCIAL =
ZOSTB_CONSEXTSUN-ZZ_NCOMERCIAL .
ZOSVA_CONSEXTSUN-ZZ_SOCIEDAD =
ZOSTB_CONSEXTSUN-ZZ_SOCIEDAD .
ZOSVA_CONSEXTSUN-ZZ_UBIGEO =
ZOSTB_CONSEXTSUN-ZZ_UBIGEO .
ZOSVA_CONSEXTSUN-ZZ_DIRECCION =
ZOSTB_CONSEXTSUN-ZZ_DIRECCION .
ZOSVA_CONSEXTSUN-ZZ_URBANIZACION =
ZOSTB_CONSEXTSUN-ZZ_URBANIZACION .
ZOSVA_CONSEXTSUN-ZZ_PROVINCIA =
ZOSTB_CONSEXTSUN-ZZ_PROVINCIA .
ZOSVA_CONSEXTSUN-ZZ_DEPARTAMENTO =
ZOSTB_CONSEXTSUN-ZZ_DEPARTAMENTO .
ZOSVA_CONSEXTSUN-ZZ_DISTRITO =
ZOSTB_CONSEXTSUN-ZZ_DISTRITO .
ZOSVA_CONSEXTSUN-ZZ_PAIS =
ZOSTB_CONSEXTSUN-ZZ_PAIS .
ZOSVA_CONSEXTSUN-ZZ_USUARIO_WEB =
ZOSTB_CONSEXTSUN-ZZ_USUARIO_WEB .
ZOSVA_CONSEXTSUN-ZZ_PASS_WEB =
ZOSTB_CONSEXTSUN-ZZ_PASS_WEB .
ZOSVA_CONSEXTSUN-ZZ_ESTAREGDOC =
ZOSTB_CONSEXTSUN-ZZ_ESTAREGDOC .
ZOSVA_CONSEXTSUN-ZZ_PROXY_NAME =
ZOSTB_CONSEXTSUN-ZZ_PROXY_NAME .
ZOSVA_CONSEXTSUN-ZZ_FACTURA =
ZOSTB_CONSEXTSUN-ZZ_FACTURA .
ZOSVA_CONSEXTSUN-ZZ_BOLETA =
ZOSTB_CONSEXTSUN-ZZ_BOLETA .
ZOSVA_CONSEXTSUN-ZZ_TDOCFACTURA =
ZOSTB_CONSEXTSUN-ZZ_TDOCFACTURA .
ZOSVA_CONSEXTSUN-ZZ_TDOCBOLETA =
ZOSTB_CONSEXTSUN-ZZ_TDOCBOLETA .
ZOSVA_CONSEXTSUN-ZZ_TDOCNOTACRE =
ZOSTB_CONSEXTSUN-ZZ_TDOCNOTACRE .
ZOSVA_CONSEXTSUN-ZZ_TDOCNOTADEB =
ZOSTB_CONSEXTSUN-ZZ_TDOCNOTADEB .
ZOSVA_CONSEXTSUN-ZZ_STATUS_CDR =
ZOSTB_CONSEXTSUN-ZZ_STATUS_CDR .
ZOSVA_CONSEXTSUN-ZZ_RESOL =
ZOSTB_CONSEXTSUN-ZZ_RESOL .
ZOSVA_CONSEXTSUN-ZZ_TDIDBAJ =
ZOSTB_CONSEXTSUN-ZZ_TDIDBAJ .
ZOSVA_CONSEXTSUN-ZZ_PARAMRUC =
ZOSTB_CONSEXTSUN-ZZ_PARAMRUC .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CONSEXTSUN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CONSEXTSUN-BUKRS TO
ZOSTB_CONSEXTSUN-BUKRS .
MOVE ZOSVA_CONSEXTSUN-MANDT TO
ZOSTB_CONSEXTSUN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CONSEXTSUN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CONSEXTSUN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CONSEXTSUN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
