*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZOSGF_T003_ITOP.                  " Global Data
  INCLUDE LZOSGF_T003_IUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZOSGF_T003_IF00                        . " subprograms
  INCLUDE LZOSGF_T003_II00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZOSGF_T003_IF...                  " Subprograms
* INCLUDE LZOSGF_T003_IO...                  " PBO-Modules
* INCLUDE LZOSGF_T003_II...                  " PAI-Modules
