*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO03................................*
FORM GET_DATA_ZOSVA_CATAHOMO03.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO03 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO03 .
ZOSVA_CATAHOMO03-MANDT =
ZOSTB_CATAHOMO03-MANDT .
ZOSVA_CATAHOMO03-MEINS =
ZOSTB_CATAHOMO03-MEINS .
ZOSVA_CATAHOMO03-CODSUN =
ZOSTB_CATAHOMO03-CODSUN .
    SELECT SINGLE * FROM T006 WHERE
MSEHI = ZOSTB_CATAHOMO03-MEINS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T006A WHERE
MSEHI = T006-MSEHI AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO03-MSEHT =
T006A-MSEHT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO03.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO03 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO03.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO03-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO03 WHERE
  MEINS = ZOSVA_CATAHOMO03-MEINS .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO03 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO03 WHERE
  MEINS = ZOSVA_CATAHOMO03-MEINS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO03.
    ENDIF.
ZOSTB_CATAHOMO03-MANDT =
ZOSVA_CATAHOMO03-MANDT .
ZOSTB_CATAHOMO03-MEINS =
ZOSVA_CATAHOMO03-MEINS .
ZOSTB_CATAHOMO03-CODSUN =
ZOSVA_CATAHOMO03-CODSUN .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO03 .
    ELSE.
    INSERT ZOSTB_CATAHOMO03 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO03-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO03-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO03.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO03 WHERE
MEINS = ZOSVA_CATAHOMO03-MEINS .
ZOSVA_CATAHOMO03-MANDT =
ZOSTB_CATAHOMO03-MANDT .
ZOSVA_CATAHOMO03-MEINS =
ZOSTB_CATAHOMO03-MEINS .
ZOSVA_CATAHOMO03-CODSUN =
ZOSTB_CATAHOMO03-CODSUN .
    SELECT SINGLE * FROM T006 WHERE
MSEHI = ZOSTB_CATAHOMO03-MEINS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T006A WHERE
MSEHI = T006-MSEHI AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO03-MSEHT =
T006A-MSEHT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO03-MSEHT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO03-MSEHT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO03 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO03-MEINS TO
ZOSTB_CATAHOMO03-MEINS .
MOVE ZOSVA_CATAHOMO03-MANDT TO
ZOSTB_CATAHOMO03-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO03'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO03 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO03'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO03 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO03-MANDT =
ZOSVA_CATAHOMO03-MANDT .
ZOSTB_CATAHOMO03-MEINS =
ZOSVA_CATAHOMO03-MEINS .
ZOSTB_CATAHOMO03-CODSUN =
ZOSVA_CATAHOMO03-CODSUN .
    SELECT SINGLE * FROM T006 WHERE
MSEHI = ZOSTB_CATAHOMO03-MEINS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T006A WHERE
MSEHI = T006-MSEHI AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO03-MSEHT =
T006A-MSEHT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO03-MSEHT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO03-MSEHT .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO06................................*
FORM GET_DATA_ZOSVA_CATAHOMO06.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO06 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO06 .
ZOSVA_CATAHOMO06-MANDT =
ZOSTB_CATAHOMO06-MANDT .
ZOSVA_CATAHOMO06-STCDT =
ZOSTB_CATAHOMO06-STCDT .
ZOSVA_CATAHOMO06-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO06-ZZ_CODIGO_SUNAT .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO06.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO06 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO06.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO06-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO06 WHERE
  STCDT = ZOSVA_CATAHOMO06-STCDT .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO06 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO06 WHERE
  STCDT = ZOSVA_CATAHOMO06-STCDT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO06.
    ENDIF.
ZOSTB_CATAHOMO06-MANDT =
ZOSVA_CATAHOMO06-MANDT .
ZOSTB_CATAHOMO06-STCDT =
ZOSVA_CATAHOMO06-STCDT .
ZOSTB_CATAHOMO06-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO06-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO06 .
    ELSE.
    INSERT ZOSTB_CATAHOMO06 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO06-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO06-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO06.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO06 WHERE
STCDT = ZOSVA_CATAHOMO06-STCDT .
ZOSVA_CATAHOMO06-MANDT =
ZOSTB_CATAHOMO06-MANDT .
ZOSVA_CATAHOMO06-STCDT =
ZOSTB_CATAHOMO06-STCDT .
ZOSVA_CATAHOMO06-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO06-ZZ_CODIGO_SUNAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO06 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO06-STCDT TO
ZOSTB_CATAHOMO06-STCDT .
MOVE ZOSVA_CATAHOMO06-MANDT TO
ZOSTB_CATAHOMO06-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO06'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO06 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO06'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO07................................*
FORM GET_DATA_ZOSVA_CATAHOMO07.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO07 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO07 .
ZOSVA_CATAHOMO07-MANDT =
ZOSTB_CATAHOMO07-MANDT .
ZOSVA_CATAHOMO07-TAXM1 =
ZOSTB_CATAHOMO07-TAXM1 .
ZOSVA_CATAHOMO07-AUGRU =
ZOSTB_CATAHOMO07-AUGRU .
ZOSVA_CATAHOMO07-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO07-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO07-ZZ_TRIBUTO =
ZOSTB_CATAHOMO07-ZZ_TRIBUTO .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO07.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO07 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO07.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO07-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO07 WHERE
  TAXM1 = ZOSVA_CATAHOMO07-TAXM1 AND
  AUGRU = ZOSVA_CATAHOMO07-AUGRU .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO07 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO07 WHERE
  TAXM1 = ZOSVA_CATAHOMO07-TAXM1 AND
  AUGRU = ZOSVA_CATAHOMO07-AUGRU .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO07.
    ENDIF.
ZOSTB_CATAHOMO07-MANDT =
ZOSVA_CATAHOMO07-MANDT .
ZOSTB_CATAHOMO07-TAXM1 =
ZOSVA_CATAHOMO07-TAXM1 .
ZOSTB_CATAHOMO07-AUGRU =
ZOSVA_CATAHOMO07-AUGRU .
ZOSTB_CATAHOMO07-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO07-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO07-ZZ_TRIBUTO =
ZOSVA_CATAHOMO07-ZZ_TRIBUTO .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO07 .
    ELSE.
    INSERT ZOSTB_CATAHOMO07 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO07-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO07-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO07.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO07 WHERE
TAXM1 = ZOSVA_CATAHOMO07-TAXM1 AND
AUGRU = ZOSVA_CATAHOMO07-AUGRU .
ZOSVA_CATAHOMO07-MANDT =
ZOSTB_CATAHOMO07-MANDT .
ZOSVA_CATAHOMO07-TAXM1 =
ZOSTB_CATAHOMO07-TAXM1 .
ZOSVA_CATAHOMO07-AUGRU =
ZOSTB_CATAHOMO07-AUGRU .
ZOSVA_CATAHOMO07-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO07-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO07-ZZ_TRIBUTO =
ZOSTB_CATAHOMO07-ZZ_TRIBUTO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO07 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO07-TAXM1 TO
ZOSTB_CATAHOMO07-TAXM1 .
MOVE ZOSVA_CATAHOMO07-AUGRU TO
ZOSTB_CATAHOMO07-AUGRU .
MOVE ZOSVA_CATAHOMO07-MANDT TO
ZOSTB_CATAHOMO07-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO07'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO07 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO07'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO08................................*
FORM GET_DATA_ZOSVA_CATAHOMO08.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO08 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO08 .
ZOSVA_CATAHOMO08-MANDT =
ZOSTB_CATAHOMO08-MANDT .
ZOSVA_CATAHOMO08-TAXM1 =
ZOSTB_CATAHOMO08-TAXM1 .
ZOSVA_CATAHOMO08-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO08-ZZ_CODIGO_SUNAT .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO08.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO08 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO08.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO08-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO08 WHERE
  TAXM1 = ZOSVA_CATAHOMO08-TAXM1 .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO08 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO08 WHERE
  TAXM1 = ZOSVA_CATAHOMO08-TAXM1 .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO08.
    ENDIF.
ZOSTB_CATAHOMO08-MANDT =
ZOSVA_CATAHOMO08-MANDT .
ZOSTB_CATAHOMO08-TAXM1 =
ZOSVA_CATAHOMO08-TAXM1 .
ZOSTB_CATAHOMO08-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO08-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO08 .
    ELSE.
    INSERT ZOSTB_CATAHOMO08 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO08-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO08-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO08.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO08 WHERE
TAXM1 = ZOSVA_CATAHOMO08-TAXM1 .
ZOSVA_CATAHOMO08-MANDT =
ZOSTB_CATAHOMO08-MANDT .
ZOSVA_CATAHOMO08-TAXM1 =
ZOSTB_CATAHOMO08-TAXM1 .
ZOSVA_CATAHOMO08-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO08-ZZ_CODIGO_SUNAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO08 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO08-TAXM1 TO
ZOSTB_CATAHOMO08-TAXM1 .
MOVE ZOSVA_CATAHOMO08-MANDT TO
ZOSTB_CATAHOMO08-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO08'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO08 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO08'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO09................................*
FORM GET_DATA_ZOSVA_CATAHOMO09.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO09 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO09 .
ZOSVA_CATAHOMO09-MANDT =
ZOSTB_CATAHOMO09-MANDT .
ZOSVA_CATAHOMO09-AUGRU =
ZOSTB_CATAHOMO09-AUGRU .
ZOSVA_CATAHOMO09-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO09-ZZ_CODIGO_SUNAT .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO09.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO09 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO09.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO09-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO09 WHERE
  AUGRU = ZOSVA_CATAHOMO09-AUGRU .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO09 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO09 WHERE
  AUGRU = ZOSVA_CATAHOMO09-AUGRU .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO09.
    ENDIF.
ZOSTB_CATAHOMO09-MANDT =
ZOSVA_CATAHOMO09-MANDT .
ZOSTB_CATAHOMO09-AUGRU =
ZOSVA_CATAHOMO09-AUGRU .
ZOSTB_CATAHOMO09-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO09-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO09 .
    ELSE.
    INSERT ZOSTB_CATAHOMO09 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO09-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO09-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO09.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO09 WHERE
AUGRU = ZOSVA_CATAHOMO09-AUGRU .
ZOSVA_CATAHOMO09-MANDT =
ZOSTB_CATAHOMO09-MANDT .
ZOSVA_CATAHOMO09-AUGRU =
ZOSTB_CATAHOMO09-AUGRU .
ZOSVA_CATAHOMO09-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO09-ZZ_CODIGO_SUNAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO09 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO09-AUGRU TO
ZOSTB_CATAHOMO09-AUGRU .
MOVE ZOSVA_CATAHOMO09-MANDT TO
ZOSTB_CATAHOMO09-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO09'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO09 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO09'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO10................................*
FORM GET_DATA_ZOSVA_CATAHOMO10.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO10 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO10 .
ZOSVA_CATAHOMO10-MANDT =
ZOSTB_CATAHOMO10-MANDT .
ZOSVA_CATAHOMO10-AUGRU =
ZOSTB_CATAHOMO10-AUGRU .
ZOSVA_CATAHOMO10-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO10-ZZ_CODIGO_SUNAT .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO10.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO10 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO10.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO10-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO10 WHERE
  AUGRU = ZOSVA_CATAHOMO10-AUGRU .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO10 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO10 WHERE
  AUGRU = ZOSVA_CATAHOMO10-AUGRU .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO10.
    ENDIF.
ZOSTB_CATAHOMO10-MANDT =
ZOSVA_CATAHOMO10-MANDT .
ZOSTB_CATAHOMO10-AUGRU =
ZOSVA_CATAHOMO10-AUGRU .
ZOSTB_CATAHOMO10-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO10-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO10 .
    ELSE.
    INSERT ZOSTB_CATAHOMO10 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO10-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO10-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO10.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO10 WHERE
AUGRU = ZOSVA_CATAHOMO10-AUGRU .
ZOSVA_CATAHOMO10-MANDT =
ZOSTB_CATAHOMO10-MANDT .
ZOSVA_CATAHOMO10-AUGRU =
ZOSTB_CATAHOMO10-AUGRU .
ZOSVA_CATAHOMO10-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO10-ZZ_CODIGO_SUNAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO10 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO10-AUGRU TO
ZOSTB_CATAHOMO10-AUGRU .
MOVE ZOSVA_CATAHOMO10-MANDT TO
ZOSTB_CATAHOMO10-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO10'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO10 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO10'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO12................................*
FORM GET_DATA_ZOSVA_CATAHOMO12.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO12 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO12 .
ZOSVA_CATAHOMO12-MANDT =
ZOSTB_CATAHOMO12-MANDT .
ZOSVA_CATAHOMO12-ZZ_TIP_DOC =
ZOSTB_CATAHOMO12-ZZ_TIP_DOC .
ZOSVA_CATAHOMO12-ZZ_TIDOCRE =
ZOSTB_CATAHOMO12-ZZ_TIDOCRE .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO12.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO12 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO12.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO12-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO12 WHERE
  ZZ_TIP_DOC = ZOSVA_CATAHOMO12-ZZ_TIP_DOC .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO12 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO12 WHERE
  ZZ_TIP_DOC = ZOSVA_CATAHOMO12-ZZ_TIP_DOC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO12.
    ENDIF.
ZOSTB_CATAHOMO12-MANDT =
ZOSVA_CATAHOMO12-MANDT .
ZOSTB_CATAHOMO12-ZZ_TIP_DOC =
ZOSVA_CATAHOMO12-ZZ_TIP_DOC .
ZOSTB_CATAHOMO12-ZZ_TIDOCRE =
ZOSVA_CATAHOMO12-ZZ_TIDOCRE .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO12 .
    ELSE.
    INSERT ZOSTB_CATAHOMO12 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO12-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO12-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO12.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO12 WHERE
ZZ_TIP_DOC = ZOSVA_CATAHOMO12-ZZ_TIP_DOC .
ZOSVA_CATAHOMO12-MANDT =
ZOSTB_CATAHOMO12-MANDT .
ZOSVA_CATAHOMO12-ZZ_TIP_DOC =
ZOSTB_CATAHOMO12-ZZ_TIP_DOC .
ZOSVA_CATAHOMO12-ZZ_TIDOCRE =
ZOSTB_CATAHOMO12-ZZ_TIDOCRE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO12 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO12-ZZ_TIP_DOC TO
ZOSTB_CATAHOMO12-ZZ_TIP_DOC .
MOVE ZOSVA_CATAHOMO12-MANDT TO
ZOSTB_CATAHOMO12-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO12'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO12 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO12'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO15................................*
FORM GET_DATA_ZOSVA_CATAHOMO15.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO15 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO15 .
ZOSVA_CATAHOMO15-MANDT =
ZOSTB_CATAHOMO15-MANDT .
ZOSVA_CATAHOMO15-BUKRS =
ZOSTB_CATAHOMO15-BUKRS .
ZOSVA_CATAHOMO15-WITHT =
ZOSTB_CATAHOMO15-WITHT .
ZOSVA_CATAHOMO15-WT_WITHCD =
ZOSTB_CATAHOMO15-WT_WITHCD .
ZOSVA_CATAHOMO15-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO15-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO15-ZZ_TEXT_CLIE =
ZOSTB_CATAHOMO15-ZZ_TEXT_CLIE .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO15-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO15-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO15-TEXT40 =
T059ZT-TEXT40 .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO15.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO15 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO15.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO15-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO15 WHERE
  BUKRS = ZOSVA_CATAHOMO15-BUKRS AND
  WITHT = ZOSVA_CATAHOMO15-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO15-WT_WITHCD .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO15 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO15 WHERE
  BUKRS = ZOSVA_CATAHOMO15-BUKRS AND
  WITHT = ZOSVA_CATAHOMO15-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO15-WT_WITHCD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO15.
    ENDIF.
ZOSTB_CATAHOMO15-MANDT =
ZOSVA_CATAHOMO15-MANDT .
ZOSTB_CATAHOMO15-BUKRS =
ZOSVA_CATAHOMO15-BUKRS .
ZOSTB_CATAHOMO15-WITHT =
ZOSVA_CATAHOMO15-WITHT .
ZOSTB_CATAHOMO15-WT_WITHCD =
ZOSVA_CATAHOMO15-WT_WITHCD .
ZOSTB_CATAHOMO15-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO15-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO15-ZZ_TEXT_CLIE =
ZOSVA_CATAHOMO15-ZZ_TEXT_CLIE .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO15 .
    ELSE.
    INSERT ZOSTB_CATAHOMO15 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO15-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO15-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO15.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO15 WHERE
BUKRS = ZOSVA_CATAHOMO15-BUKRS AND
WITHT = ZOSVA_CATAHOMO15-WITHT AND
WT_WITHCD = ZOSVA_CATAHOMO15-WT_WITHCD .
ZOSVA_CATAHOMO15-MANDT =
ZOSTB_CATAHOMO15-MANDT .
ZOSVA_CATAHOMO15-BUKRS =
ZOSTB_CATAHOMO15-BUKRS .
ZOSVA_CATAHOMO15-WITHT =
ZOSTB_CATAHOMO15-WITHT .
ZOSVA_CATAHOMO15-WT_WITHCD =
ZOSTB_CATAHOMO15-WT_WITHCD .
ZOSVA_CATAHOMO15-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO15-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO15-ZZ_TEXT_CLIE =
ZOSTB_CATAHOMO15-ZZ_TEXT_CLIE .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO15-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO15-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO15-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO15-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO15-TEXT40 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO15 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO15-BUKRS TO
ZOSTB_CATAHOMO15-BUKRS .
MOVE ZOSVA_CATAHOMO15-WITHT TO
ZOSTB_CATAHOMO15-WITHT .
MOVE ZOSVA_CATAHOMO15-WT_WITHCD TO
ZOSTB_CATAHOMO15-WT_WITHCD .
MOVE ZOSVA_CATAHOMO15-MANDT TO
ZOSTB_CATAHOMO15-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO15'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO15 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO15'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO15 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO15-MANDT =
ZOSVA_CATAHOMO15-MANDT .
ZOSTB_CATAHOMO15-BUKRS =
ZOSVA_CATAHOMO15-BUKRS .
ZOSTB_CATAHOMO15-WITHT =
ZOSVA_CATAHOMO15-WITHT .
ZOSTB_CATAHOMO15-WT_WITHCD =
ZOSVA_CATAHOMO15-WT_WITHCD .
ZOSTB_CATAHOMO15-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO15-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO15-ZZ_TEXT_CLIE =
ZOSVA_CATAHOMO15-ZZ_TEXT_CLIE .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO15-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO15-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO15-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO15-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO15-TEXT40 .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO18................................*
FORM GET_DATA_ZOSVA_CATAHOMO18.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO18 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO18 .
ZOSVA_CATAHOMO18-MANDT =
ZOSTB_CATAHOMO18-MANDT .
ZOSVA_CATAHOMO18-SHTYP =
ZOSTB_CATAHOMO18-SHTYP .
ZOSVA_CATAHOMO18-LFART =
ZOSTB_CATAHOMO18-LFART .
ZOSVA_CATAHOMO18-TOR_TYPE =
ZOSTB_CATAHOMO18-TOR_TYPE .
ZOSVA_CATAHOMO18-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO18-ZZ_CODIGO_SUNAT .
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO18.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO18 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO18.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO18-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO18 WHERE
  SHTYP = ZOSVA_CATAHOMO18-SHTYP AND
  LFART = ZOSVA_CATAHOMO18-LFART AND
  TOR_TYPE = ZOSVA_CATAHOMO18-TOR_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO18 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO18 WHERE
  SHTYP = ZOSVA_CATAHOMO18-SHTYP AND
  LFART = ZOSVA_CATAHOMO18-LFART AND
  TOR_TYPE = ZOSVA_CATAHOMO18-TOR_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO18.
    ENDIF.
ZOSTB_CATAHOMO18-MANDT =
ZOSVA_CATAHOMO18-MANDT .
ZOSTB_CATAHOMO18-SHTYP =
ZOSVA_CATAHOMO18-SHTYP .
ZOSTB_CATAHOMO18-LFART =
ZOSVA_CATAHOMO18-LFART .
ZOSTB_CATAHOMO18-TOR_TYPE =
ZOSVA_CATAHOMO18-TOR_TYPE .
ZOSTB_CATAHOMO18-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO18-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO18 .
    ELSE.
    INSERT ZOSTB_CATAHOMO18 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO18-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO18-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO18.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO18 WHERE
SHTYP = ZOSVA_CATAHOMO18-SHTYP AND
LFART = ZOSVA_CATAHOMO18-LFART AND
TOR_TYPE = ZOSVA_CATAHOMO18-TOR_TYPE .
ZOSVA_CATAHOMO18-MANDT =
ZOSTB_CATAHOMO18-MANDT .
ZOSVA_CATAHOMO18-SHTYP =
ZOSTB_CATAHOMO18-SHTYP .
ZOSVA_CATAHOMO18-LFART =
ZOSTB_CATAHOMO18-LFART .
ZOSVA_CATAHOMO18-TOR_TYPE =
ZOSTB_CATAHOMO18-TOR_TYPE .
ZOSVA_CATAHOMO18-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO18-ZZ_CODIGO_SUNAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO18 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO18-SHTYP TO
ZOSTB_CATAHOMO18-SHTYP .
MOVE ZOSVA_CATAHOMO18-LFART TO
ZOSTB_CATAHOMO18-LFART .
MOVE ZOSVA_CATAHOMO18-TOR_TYPE TO
ZOSTB_CATAHOMO18-TOR_TYPE .
MOVE ZOSVA_CATAHOMO18-MANDT TO
ZOSTB_CATAHOMO18-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO18'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO18 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO18'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO20................................*
FORM GET_DATA_ZOSVA_CATAHOMO20.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO20 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO20 .
ZOSVA_CATAHOMO20-MANDT =
ZOSTB_CATAHOMO20-MANDT .
ZOSVA_CATAHOMO20-LFART =
ZOSTB_CATAHOMO20-LFART .
ZOSVA_CATAHOMO20-KVGR1 =
ZOSTB_CATAHOMO20-KVGR1 .
ZOSVA_CATAHOMO20-KVGR2 =
ZOSTB_CATAHOMO20-KVGR2 .
ZOSVA_CATAHOMO20-AUART =
ZOSTB_CATAHOMO20-AUART .
ZOSVA_CATAHOMO20-BSART =
ZOSTB_CATAHOMO20-BSART .
ZOSVA_CATAHOMO20-BWART =
ZOSTB_CATAHOMO20-BWART .
ZOSVA_CATAHOMO20-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO20-ZZ_DESC_COD_SUNA =
ZOSTB_CATAHOMO20-ZZ_DESC_COD_SUNA .
    SELECT SINGLE * FROM ZOSTB_CATALOGO20 WHERE
ZZ_CODIGO_SUNAT = ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO20-IS_DESC_CUST =
ZOSTB_CATALOGO20-IS_DESC_CUST .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO20.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO20 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO20.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO20-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO20 WHERE
  LFART = ZOSVA_CATAHOMO20-LFART AND
  KVGR1 = ZOSVA_CATAHOMO20-KVGR1 AND
  KVGR2 = ZOSVA_CATAHOMO20-KVGR2 AND
  AUART = ZOSVA_CATAHOMO20-AUART AND
  BSART = ZOSVA_CATAHOMO20-BSART AND
  BWART = ZOSVA_CATAHOMO20-BWART .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO20 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO20 WHERE
  LFART = ZOSVA_CATAHOMO20-LFART AND
  KVGR1 = ZOSVA_CATAHOMO20-KVGR1 AND
  KVGR2 = ZOSVA_CATAHOMO20-KVGR2 AND
  AUART = ZOSVA_CATAHOMO20-AUART AND
  BSART = ZOSVA_CATAHOMO20-BSART AND
  BWART = ZOSVA_CATAHOMO20-BWART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO20.
    ENDIF.
ZOSTB_CATAHOMO20-MANDT =
ZOSVA_CATAHOMO20-MANDT .
ZOSTB_CATAHOMO20-LFART =
ZOSVA_CATAHOMO20-LFART .
ZOSTB_CATAHOMO20-KVGR1 =
ZOSVA_CATAHOMO20-KVGR1 .
ZOSTB_CATAHOMO20-KVGR2 =
ZOSVA_CATAHOMO20-KVGR2 .
ZOSTB_CATAHOMO20-AUART =
ZOSVA_CATAHOMO20-AUART .
ZOSTB_CATAHOMO20-BSART =
ZOSVA_CATAHOMO20-BSART .
ZOSTB_CATAHOMO20-BWART =
ZOSVA_CATAHOMO20-BWART .
ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO20-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO20-ZZ_DESC_COD_SUNA =
ZOSVA_CATAHOMO20-ZZ_DESC_COD_SUNA .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO20 .
    ELSE.
    INSERT ZOSTB_CATAHOMO20 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO20-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO20-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO20.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO20 WHERE
LFART = ZOSVA_CATAHOMO20-LFART AND
KVGR1 = ZOSVA_CATAHOMO20-KVGR1 AND
KVGR2 = ZOSVA_CATAHOMO20-KVGR2 AND
AUART = ZOSVA_CATAHOMO20-AUART AND
BSART = ZOSVA_CATAHOMO20-BSART AND
BWART = ZOSVA_CATAHOMO20-BWART .
ZOSVA_CATAHOMO20-MANDT =
ZOSTB_CATAHOMO20-MANDT .
ZOSVA_CATAHOMO20-LFART =
ZOSTB_CATAHOMO20-LFART .
ZOSVA_CATAHOMO20-KVGR1 =
ZOSTB_CATAHOMO20-KVGR1 .
ZOSVA_CATAHOMO20-KVGR2 =
ZOSTB_CATAHOMO20-KVGR2 .
ZOSVA_CATAHOMO20-AUART =
ZOSTB_CATAHOMO20-AUART .
ZOSVA_CATAHOMO20-BSART =
ZOSTB_CATAHOMO20-BSART .
ZOSVA_CATAHOMO20-BWART =
ZOSTB_CATAHOMO20-BWART .
ZOSVA_CATAHOMO20-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO20-ZZ_DESC_COD_SUNA =
ZOSTB_CATAHOMO20-ZZ_DESC_COD_SUNA .
    SELECT SINGLE * FROM ZOSTB_CATALOGO20 WHERE
ZZ_CODIGO_SUNAT = ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO20-IS_DESC_CUST =
ZOSTB_CATALOGO20-IS_DESC_CUST .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO20-IS_DESC_CUST .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO20 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO20-LFART TO
ZOSTB_CATAHOMO20-LFART .
MOVE ZOSVA_CATAHOMO20-KVGR1 TO
ZOSTB_CATAHOMO20-KVGR1 .
MOVE ZOSVA_CATAHOMO20-KVGR2 TO
ZOSTB_CATAHOMO20-KVGR2 .
MOVE ZOSVA_CATAHOMO20-AUART TO
ZOSTB_CATAHOMO20-AUART .
MOVE ZOSVA_CATAHOMO20-BSART TO
ZOSTB_CATAHOMO20-BSART .
MOVE ZOSVA_CATAHOMO20-BWART TO
ZOSTB_CATAHOMO20-BWART .
MOVE ZOSVA_CATAHOMO20-MANDT TO
ZOSTB_CATAHOMO20-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO20'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO20 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO20'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO20 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO20-MANDT =
ZOSVA_CATAHOMO20-MANDT .
ZOSTB_CATAHOMO20-LFART =
ZOSVA_CATAHOMO20-LFART .
ZOSTB_CATAHOMO20-KVGR1 =
ZOSVA_CATAHOMO20-KVGR1 .
ZOSTB_CATAHOMO20-KVGR2 =
ZOSVA_CATAHOMO20-KVGR2 .
ZOSTB_CATAHOMO20-AUART =
ZOSVA_CATAHOMO20-AUART .
ZOSTB_CATAHOMO20-BSART =
ZOSVA_CATAHOMO20-BSART .
ZOSTB_CATAHOMO20-BWART =
ZOSVA_CATAHOMO20-BWART .
ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO20-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO20-ZZ_DESC_COD_SUNA =
ZOSVA_CATAHOMO20-ZZ_DESC_COD_SUNA .
    SELECT SINGLE * FROM ZOSTB_CATALOGO20 WHERE
ZZ_CODIGO_SUNAT = ZOSTB_CATAHOMO20-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO20-IS_DESC_CUST =
ZOSTB_CATALOGO20-IS_DESC_CUST .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO20-IS_DESC_CUST .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO22................................*
FORM GET_DATA_ZOSVA_CATAHOMO22.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO22 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO22 .
ZOSVA_CATAHOMO22-MANDT =
ZOSTB_CATAHOMO22-MANDT .
ZOSVA_CATAHOMO22-WITHT =
ZOSTB_CATAHOMO22-WITHT .
ZOSVA_CATAHOMO22-WT_WITHCD =
ZOSTB_CATAHOMO22-WT_WITHCD .
ZOSVA_CATAHOMO22-CODSUN =
ZOSTB_CATAHOMO22-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO22-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO22-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO22-TEXT40 =
T059ZT-TEXT40 .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO22 WHERE
CODSUN = ZOSTB_CATAHOMO22-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO22-DESSUN =
ZOSTB_CATALOGO22-DESSUN .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO22.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO22 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO22.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO22-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO22 WHERE
  WITHT = ZOSVA_CATAHOMO22-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO22-WT_WITHCD .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO22 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO22 WHERE
  WITHT = ZOSVA_CATAHOMO22-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO22-WT_WITHCD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO22.
    ENDIF.
ZOSTB_CATAHOMO22-MANDT =
ZOSVA_CATAHOMO22-MANDT .
ZOSTB_CATAHOMO22-WITHT =
ZOSVA_CATAHOMO22-WITHT .
ZOSTB_CATAHOMO22-WT_WITHCD =
ZOSVA_CATAHOMO22-WT_WITHCD .
ZOSTB_CATAHOMO22-CODSUN =
ZOSVA_CATAHOMO22-CODSUN .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO22 .
    ELSE.
    INSERT ZOSTB_CATAHOMO22 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO22-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO22-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO22.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO22 WHERE
WITHT = ZOSVA_CATAHOMO22-WITHT AND
WT_WITHCD = ZOSVA_CATAHOMO22-WT_WITHCD .
ZOSVA_CATAHOMO22-MANDT =
ZOSTB_CATAHOMO22-MANDT .
ZOSVA_CATAHOMO22-WITHT =
ZOSTB_CATAHOMO22-WITHT .
ZOSVA_CATAHOMO22-WT_WITHCD =
ZOSTB_CATAHOMO22-WT_WITHCD .
ZOSVA_CATAHOMO22-CODSUN =
ZOSTB_CATAHOMO22-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO22-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO22-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO22-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO22-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO22-TEXT40 .
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO22 WHERE
CODSUN = ZOSTB_CATAHOMO22-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO22-DESSUN =
ZOSTB_CATALOGO22-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO22-DESSUN .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO22 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO22-WITHT TO
ZOSTB_CATAHOMO22-WITHT .
MOVE ZOSVA_CATAHOMO22-WT_WITHCD TO
ZOSTB_CATAHOMO22-WT_WITHCD .
MOVE ZOSVA_CATAHOMO22-MANDT TO
ZOSTB_CATAHOMO22-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO22'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO22 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO22'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO22 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO22-MANDT =
ZOSVA_CATAHOMO22-MANDT .
ZOSTB_CATAHOMO22-WITHT =
ZOSVA_CATAHOMO22-WITHT .
ZOSTB_CATAHOMO22-WT_WITHCD =
ZOSVA_CATAHOMO22-WT_WITHCD .
ZOSTB_CATAHOMO22-CODSUN =
ZOSVA_CATAHOMO22-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO22-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO22-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO22-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO22-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO22-TEXT40 .
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO22 WHERE
CODSUN = ZOSTB_CATAHOMO22-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO22-DESSUN =
ZOSTB_CATALOGO22-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO22-DESSUN .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO23................................*
FORM GET_DATA_ZOSVA_CATAHOMO23.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO23 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO23 .
ZOSVA_CATAHOMO23-MANDT =
ZOSTB_CATAHOMO23-MANDT .
ZOSVA_CATAHOMO23-WITHT =
ZOSTB_CATAHOMO23-WITHT .
ZOSVA_CATAHOMO23-WT_WITHCD =
ZOSTB_CATAHOMO23-WT_WITHCD .
ZOSVA_CATAHOMO23-CODSUN =
ZOSTB_CATAHOMO23-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO23-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO23-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO23-TEXT40 =
T059ZT-TEXT40 .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO23 WHERE
CODSUN = ZOSTB_CATAHOMO23-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO23-DESSUN =
ZOSTB_CATALOGO23-DESSUN .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO23.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO23 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO23.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO23-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO23 WHERE
  WITHT = ZOSVA_CATAHOMO23-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO23-WT_WITHCD .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO23 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO23 WHERE
  WITHT = ZOSVA_CATAHOMO23-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO23-WT_WITHCD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO23.
    ENDIF.
ZOSTB_CATAHOMO23-MANDT =
ZOSVA_CATAHOMO23-MANDT .
ZOSTB_CATAHOMO23-WITHT =
ZOSVA_CATAHOMO23-WITHT .
ZOSTB_CATAHOMO23-WT_WITHCD =
ZOSVA_CATAHOMO23-WT_WITHCD .
ZOSTB_CATAHOMO23-CODSUN =
ZOSVA_CATAHOMO23-CODSUN .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO23 .
    ELSE.
    INSERT ZOSTB_CATAHOMO23 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO23-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO23-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO23.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO23 WHERE
WITHT = ZOSVA_CATAHOMO23-WITHT AND
WT_WITHCD = ZOSVA_CATAHOMO23-WT_WITHCD .
ZOSVA_CATAHOMO23-MANDT =
ZOSTB_CATAHOMO23-MANDT .
ZOSVA_CATAHOMO23-WITHT =
ZOSTB_CATAHOMO23-WITHT .
ZOSVA_CATAHOMO23-WT_WITHCD =
ZOSTB_CATAHOMO23-WT_WITHCD .
ZOSVA_CATAHOMO23-CODSUN =
ZOSTB_CATAHOMO23-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO23-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO23-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO23-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO23-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO23-TEXT40 .
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO23 WHERE
CODSUN = ZOSTB_CATAHOMO23-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO23-DESSUN =
ZOSTB_CATALOGO23-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO23-DESSUN .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO23 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO23-WITHT TO
ZOSTB_CATAHOMO23-WITHT .
MOVE ZOSVA_CATAHOMO23-WT_WITHCD TO
ZOSTB_CATAHOMO23-WT_WITHCD .
MOVE ZOSVA_CATAHOMO23-MANDT TO
ZOSTB_CATAHOMO23-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO23'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO23 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO23'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO23 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO23-MANDT =
ZOSVA_CATAHOMO23-MANDT .
ZOSTB_CATAHOMO23-WITHT =
ZOSVA_CATAHOMO23-WITHT .
ZOSTB_CATAHOMO23-WT_WITHCD =
ZOSVA_CATAHOMO23-WT_WITHCD .
ZOSTB_CATAHOMO23-CODSUN =
ZOSVA_CATAHOMO23-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO23-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO23-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO23-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO23-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO23-TEXT40 .
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO23 WHERE
CODSUN = ZOSTB_CATAHOMO23-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO23-DESSUN =
ZOSTB_CATALOGO23-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO23-DESSUN .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO51................................*
FORM GET_DATA_ZOSVA_CATAHOMO51.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO51 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO51 .
ZOSVA_CATAHOMO51-MANDT =
ZOSTB_CATAHOMO51-MANDT .
ZOSVA_CATAHOMO51-LAND1 =
ZOSTB_CATAHOMO51-LAND1 .
ZOSVA_CATAHOMO51-WITHT =
ZOSTB_CATAHOMO51-WITHT .
ZOSVA_CATAHOMO51-WT_WITHCD =
ZOSTB_CATAHOMO51-WT_WITHCD .
ZOSVA_CATAHOMO51-PSTYV =
ZOSTB_CATAHOMO51-PSTYV .
ZOSVA_CATAHOMO51-AUGRU =
ZOSTB_CATAHOMO51-AUGRU .
ZOSVA_CATAHOMO51-MTART =
ZOSTB_CATAHOMO51-MTART .
ZOSVA_CATAHOMO51-CODSUN =
ZOSTB_CATAHOMO51-CODSUN .
    SELECT SINGLE * FROM ZOSTB_CATALOGO51 WHERE
CODSUN = ZOSTB_CATAHOMO51-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO51-DESSUN =
ZOSTB_CATALOGO51-DESSUN .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO51.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO51 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO51.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO51-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO51 WHERE
  LAND1 = ZOSVA_CATAHOMO51-LAND1 AND
  WITHT = ZOSVA_CATAHOMO51-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO51-WT_WITHCD AND
  PSTYV = ZOSVA_CATAHOMO51-PSTYV AND
  AUGRU = ZOSVA_CATAHOMO51-AUGRU AND
  MTART = ZOSVA_CATAHOMO51-MTART .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO51 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO51 WHERE
  LAND1 = ZOSVA_CATAHOMO51-LAND1 AND
  WITHT = ZOSVA_CATAHOMO51-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO51-WT_WITHCD AND
  PSTYV = ZOSVA_CATAHOMO51-PSTYV AND
  AUGRU = ZOSVA_CATAHOMO51-AUGRU AND
  MTART = ZOSVA_CATAHOMO51-MTART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO51.
    ENDIF.
ZOSTB_CATAHOMO51-MANDT =
ZOSVA_CATAHOMO51-MANDT .
ZOSTB_CATAHOMO51-LAND1 =
ZOSVA_CATAHOMO51-LAND1 .
ZOSTB_CATAHOMO51-WITHT =
ZOSVA_CATAHOMO51-WITHT .
ZOSTB_CATAHOMO51-WT_WITHCD =
ZOSVA_CATAHOMO51-WT_WITHCD .
ZOSTB_CATAHOMO51-PSTYV =
ZOSVA_CATAHOMO51-PSTYV .
ZOSTB_CATAHOMO51-AUGRU =
ZOSVA_CATAHOMO51-AUGRU .
ZOSTB_CATAHOMO51-MTART =
ZOSVA_CATAHOMO51-MTART .
ZOSTB_CATAHOMO51-CODSUN =
ZOSVA_CATAHOMO51-CODSUN .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO51 .
    ELSE.
    INSERT ZOSTB_CATAHOMO51 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO51-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO51-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO51.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO51 WHERE
LAND1 = ZOSVA_CATAHOMO51-LAND1 AND
WITHT = ZOSVA_CATAHOMO51-WITHT AND
WT_WITHCD = ZOSVA_CATAHOMO51-WT_WITHCD AND
PSTYV = ZOSVA_CATAHOMO51-PSTYV AND
AUGRU = ZOSVA_CATAHOMO51-AUGRU AND
MTART = ZOSVA_CATAHOMO51-MTART .
ZOSVA_CATAHOMO51-MANDT =
ZOSTB_CATAHOMO51-MANDT .
ZOSVA_CATAHOMO51-LAND1 =
ZOSTB_CATAHOMO51-LAND1 .
ZOSVA_CATAHOMO51-WITHT =
ZOSTB_CATAHOMO51-WITHT .
ZOSVA_CATAHOMO51-WT_WITHCD =
ZOSTB_CATAHOMO51-WT_WITHCD .
ZOSVA_CATAHOMO51-PSTYV =
ZOSTB_CATAHOMO51-PSTYV .
ZOSVA_CATAHOMO51-AUGRU =
ZOSTB_CATAHOMO51-AUGRU .
ZOSVA_CATAHOMO51-MTART =
ZOSTB_CATAHOMO51-MTART .
ZOSVA_CATAHOMO51-CODSUN =
ZOSTB_CATAHOMO51-CODSUN .
    SELECT SINGLE * FROM ZOSTB_CATALOGO51 WHERE
CODSUN = ZOSTB_CATAHOMO51-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO51-DESSUN =
ZOSTB_CATALOGO51-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO51-DESSUN .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO51 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO51-LAND1 TO
ZOSTB_CATAHOMO51-LAND1 .
MOVE ZOSVA_CATAHOMO51-WITHT TO
ZOSTB_CATAHOMO51-WITHT .
MOVE ZOSVA_CATAHOMO51-WT_WITHCD TO
ZOSTB_CATAHOMO51-WT_WITHCD .
MOVE ZOSVA_CATAHOMO51-PSTYV TO
ZOSTB_CATAHOMO51-PSTYV .
MOVE ZOSVA_CATAHOMO51-AUGRU TO
ZOSTB_CATAHOMO51-AUGRU .
MOVE ZOSVA_CATAHOMO51-MTART TO
ZOSTB_CATAHOMO51-MTART .
MOVE ZOSVA_CATAHOMO51-MANDT TO
ZOSTB_CATAHOMO51-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO51'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO51 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO51'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO51 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO51-MANDT =
ZOSVA_CATAHOMO51-MANDT .
ZOSTB_CATAHOMO51-LAND1 =
ZOSVA_CATAHOMO51-LAND1 .
ZOSTB_CATAHOMO51-WITHT =
ZOSVA_CATAHOMO51-WITHT .
ZOSTB_CATAHOMO51-WT_WITHCD =
ZOSVA_CATAHOMO51-WT_WITHCD .
ZOSTB_CATAHOMO51-PSTYV =
ZOSVA_CATAHOMO51-PSTYV .
ZOSTB_CATAHOMO51-AUGRU =
ZOSVA_CATAHOMO51-AUGRU .
ZOSTB_CATAHOMO51-MTART =
ZOSVA_CATAHOMO51-MTART .
ZOSTB_CATAHOMO51-CODSUN =
ZOSVA_CATAHOMO51-CODSUN .
    SELECT SINGLE * FROM ZOSTB_CATALOGO51 WHERE
CODSUN = ZOSTB_CATAHOMO51-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO51-DESSUN =
ZOSTB_CATALOGO51-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO51-DESSUN .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO53................................*
FORM GET_DATA_ZOSVA_CATAHOMO53.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO53 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO53 .
ZOSVA_CATAHOMO53-MANDT =
ZOSTB_CATAHOMO53-MANDT .
ZOSVA_CATAHOMO53-KSCHL =
ZOSTB_CATAHOMO53-KSCHL .
ZOSVA_CATAHOMO53-ZZ_NIVEL =
ZOSTB_CATAHOMO53-ZZ_NIVEL .
ZOSVA_CATAHOMO53-PSTYV =
ZOSTB_CATAHOMO53-PSTYV .
ZOSVA_CATAHOMO53-ZZ_CODTRIB_H =
ZOSTB_CATAHOMO53-ZZ_CODTRIB_H .
ZOSVA_CATAHOMO53-WITHT =
ZOSTB_CATAHOMO53-WITHT .
ZOSVA_CATAHOMO53-WT_WITHCD =
ZOSTB_CATAHOMO53-WT_WITHCD .
ZOSVA_CATAHOMO53-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO53-ZZ_CHARGEINDICADOR =
ZOSTB_CATAHOMO53-ZZ_CHARGEINDICADOR .
ZOSVA_CATAHOMO53-ZZ_CARGO_CHECK =
ZOSTB_CATAHOMO53-ZZ_CARGO_CHECK .
    SELECT SINGLE * FROM ZOSTB_CATALOGO53 WHERE
ZZ_CODIGO_SUNAT = ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO53-ZZ_DESC_COD_SUNA =
ZOSTB_CATALOGO53-ZZ_DESC_COD_SUNA .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO53.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO53 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO53.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO53-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO53 WHERE
  KSCHL = ZOSVA_CATAHOMO53-KSCHL AND
  ZZ_NIVEL = ZOSVA_CATAHOMO53-ZZ_NIVEL AND
  PSTYV = ZOSVA_CATAHOMO53-PSTYV AND
  ZZ_CODTRIB_H = ZOSVA_CATAHOMO53-ZZ_CODTRIB_H AND
  WITHT = ZOSVA_CATAHOMO53-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO53-WT_WITHCD .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO53 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO53 WHERE
  KSCHL = ZOSVA_CATAHOMO53-KSCHL AND
  ZZ_NIVEL = ZOSVA_CATAHOMO53-ZZ_NIVEL AND
  PSTYV = ZOSVA_CATAHOMO53-PSTYV AND
  ZZ_CODTRIB_H = ZOSVA_CATAHOMO53-ZZ_CODTRIB_H AND
  WITHT = ZOSVA_CATAHOMO53-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO53-WT_WITHCD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO53.
    ENDIF.
ZOSTB_CATAHOMO53-MANDT =
ZOSVA_CATAHOMO53-MANDT .
ZOSTB_CATAHOMO53-KSCHL =
ZOSVA_CATAHOMO53-KSCHL .
ZOSTB_CATAHOMO53-ZZ_NIVEL =
ZOSVA_CATAHOMO53-ZZ_NIVEL .
ZOSTB_CATAHOMO53-PSTYV =
ZOSVA_CATAHOMO53-PSTYV .
ZOSTB_CATAHOMO53-ZZ_CODTRIB_H =
ZOSVA_CATAHOMO53-ZZ_CODTRIB_H .
ZOSTB_CATAHOMO53-WITHT =
ZOSVA_CATAHOMO53-WITHT .
ZOSTB_CATAHOMO53-WT_WITHCD =
ZOSVA_CATAHOMO53-WT_WITHCD .
ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO53-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO53-ZZ_CHARGEINDICADOR =
ZOSVA_CATAHOMO53-ZZ_CHARGEINDICADOR .
ZOSTB_CATAHOMO53-ZZ_CARGO_CHECK =
ZOSVA_CATAHOMO53-ZZ_CARGO_CHECK .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO53 .
    ELSE.
    INSERT ZOSTB_CATAHOMO53 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO53-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO53-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO53.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO53 WHERE
KSCHL = ZOSVA_CATAHOMO53-KSCHL AND
ZZ_NIVEL = ZOSVA_CATAHOMO53-ZZ_NIVEL AND
PSTYV = ZOSVA_CATAHOMO53-PSTYV AND
ZZ_CODTRIB_H = ZOSVA_CATAHOMO53-ZZ_CODTRIB_H AND
WITHT = ZOSVA_CATAHOMO53-WITHT AND
WT_WITHCD = ZOSVA_CATAHOMO53-WT_WITHCD .
ZOSVA_CATAHOMO53-MANDT =
ZOSTB_CATAHOMO53-MANDT .
ZOSVA_CATAHOMO53-KSCHL =
ZOSTB_CATAHOMO53-KSCHL .
ZOSVA_CATAHOMO53-ZZ_NIVEL =
ZOSTB_CATAHOMO53-ZZ_NIVEL .
ZOSVA_CATAHOMO53-PSTYV =
ZOSTB_CATAHOMO53-PSTYV .
ZOSVA_CATAHOMO53-ZZ_CODTRIB_H =
ZOSTB_CATAHOMO53-ZZ_CODTRIB_H .
ZOSVA_CATAHOMO53-WITHT =
ZOSTB_CATAHOMO53-WITHT .
ZOSVA_CATAHOMO53-WT_WITHCD =
ZOSTB_CATAHOMO53-WT_WITHCD .
ZOSVA_CATAHOMO53-ZZ_CODIGO_SUNAT =
ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT .
ZOSVA_CATAHOMO53-ZZ_CHARGEINDICADOR =
ZOSTB_CATAHOMO53-ZZ_CHARGEINDICADOR .
ZOSVA_CATAHOMO53-ZZ_CARGO_CHECK =
ZOSTB_CATAHOMO53-ZZ_CARGO_CHECK .
    SELECT SINGLE * FROM ZOSTB_CATALOGO53 WHERE
ZZ_CODIGO_SUNAT = ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO53-ZZ_DESC_COD_SUNA =
ZOSTB_CATALOGO53-ZZ_DESC_COD_SUNA .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO53-ZZ_DESC_COD_SUNA .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO53 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO53-KSCHL TO
ZOSTB_CATAHOMO53-KSCHL .
MOVE ZOSVA_CATAHOMO53-ZZ_NIVEL TO
ZOSTB_CATAHOMO53-ZZ_NIVEL .
MOVE ZOSVA_CATAHOMO53-PSTYV TO
ZOSTB_CATAHOMO53-PSTYV .
MOVE ZOSVA_CATAHOMO53-ZZ_CODTRIB_H TO
ZOSTB_CATAHOMO53-ZZ_CODTRIB_H .
MOVE ZOSVA_CATAHOMO53-WITHT TO
ZOSTB_CATAHOMO53-WITHT .
MOVE ZOSVA_CATAHOMO53-WT_WITHCD TO
ZOSTB_CATAHOMO53-WT_WITHCD .
MOVE ZOSVA_CATAHOMO53-MANDT TO
ZOSTB_CATAHOMO53-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO53'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO53 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO53'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO53 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO53-MANDT =
ZOSVA_CATAHOMO53-MANDT .
ZOSTB_CATAHOMO53-KSCHL =
ZOSVA_CATAHOMO53-KSCHL .
ZOSTB_CATAHOMO53-ZZ_NIVEL =
ZOSVA_CATAHOMO53-ZZ_NIVEL .
ZOSTB_CATAHOMO53-PSTYV =
ZOSVA_CATAHOMO53-PSTYV .
ZOSTB_CATAHOMO53-ZZ_CODTRIB_H =
ZOSVA_CATAHOMO53-ZZ_CODTRIB_H .
ZOSTB_CATAHOMO53-WITHT =
ZOSVA_CATAHOMO53-WITHT .
ZOSTB_CATAHOMO53-WT_WITHCD =
ZOSVA_CATAHOMO53-WT_WITHCD .
ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT =
ZOSVA_CATAHOMO53-ZZ_CODIGO_SUNAT .
ZOSTB_CATAHOMO53-ZZ_CHARGEINDICADOR =
ZOSVA_CATAHOMO53-ZZ_CHARGEINDICADOR .
ZOSTB_CATAHOMO53-ZZ_CARGO_CHECK =
ZOSVA_CATAHOMO53-ZZ_CARGO_CHECK .
    SELECT SINGLE * FROM ZOSTB_CATALOGO53 WHERE
ZZ_CODIGO_SUNAT = ZOSTB_CATAHOMO53-ZZ_CODIGO_SUNAT .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO53-ZZ_DESC_COD_SUNA =
ZOSTB_CATALOGO53-ZZ_DESC_COD_SUNA .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO53-ZZ_DESC_COD_SUNA .
    ENDIF.
ENDFORM.
*...processing: ZOSVA_CATAHOMO54................................*
FORM GET_DATA_ZOSVA_CATAHOMO54.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO54 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO54 .
ZOSVA_CATAHOMO54-MANDT =
ZOSTB_CATAHOMO54-MANDT .
ZOSVA_CATAHOMO54-WITHT =
ZOSTB_CATAHOMO54-WITHT .
ZOSVA_CATAHOMO54-WT_WITHCD =
ZOSTB_CATAHOMO54-WT_WITHCD .
ZOSVA_CATAHOMO54-CODSUN =
ZOSTB_CATAHOMO54-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO54-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO54-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO54-TEXT40 =
T059ZT-TEXT40 .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO54 WHERE
CODSUN = ZOSTB_CATAHOMO54-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO54-DESSUN =
ZOSTB_CATALOGO54-DESSUN .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO54.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO54 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO54.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO54-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO54 WHERE
  WITHT = ZOSVA_CATAHOMO54-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO54-WT_WITHCD .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO54 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO54 WHERE
  WITHT = ZOSVA_CATAHOMO54-WITHT AND
  WT_WITHCD = ZOSVA_CATAHOMO54-WT_WITHCD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO54.
    ENDIF.
ZOSTB_CATAHOMO54-MANDT =
ZOSVA_CATAHOMO54-MANDT .
ZOSTB_CATAHOMO54-WITHT =
ZOSVA_CATAHOMO54-WITHT .
ZOSTB_CATAHOMO54-WT_WITHCD =
ZOSVA_CATAHOMO54-WT_WITHCD .
ZOSTB_CATAHOMO54-CODSUN =
ZOSVA_CATAHOMO54-CODSUN .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO54 .
    ELSE.
    INSERT ZOSTB_CATAHOMO54 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO54-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO54-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO54.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO54 WHERE
WITHT = ZOSVA_CATAHOMO54-WITHT AND
WT_WITHCD = ZOSVA_CATAHOMO54-WT_WITHCD .
ZOSVA_CATAHOMO54-MANDT =
ZOSTB_CATAHOMO54-MANDT .
ZOSVA_CATAHOMO54-WITHT =
ZOSTB_CATAHOMO54-WITHT .
ZOSVA_CATAHOMO54-WT_WITHCD =
ZOSTB_CATAHOMO54-WT_WITHCD .
ZOSVA_CATAHOMO54-CODSUN =
ZOSTB_CATAHOMO54-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO54-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO54-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO54-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO54-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO54-TEXT40 .
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO54 WHERE
CODSUN = ZOSTB_CATAHOMO54-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO54-DESSUN =
ZOSTB_CATALOGO54-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO54-DESSUN .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO54 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO54-WITHT TO
ZOSTB_CATAHOMO54-WITHT .
MOVE ZOSVA_CATAHOMO54-WT_WITHCD TO
ZOSTB_CATAHOMO54-WT_WITHCD .
MOVE ZOSVA_CATAHOMO54-MANDT TO
ZOSTB_CATAHOMO54-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO54'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO54 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO54'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO54 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO54-MANDT =
ZOSVA_CATAHOMO54-MANDT .
ZOSTB_CATAHOMO54-WITHT =
ZOSVA_CATAHOMO54-WITHT .
ZOSTB_CATAHOMO54-WT_WITHCD =
ZOSVA_CATAHOMO54-WT_WITHCD .
ZOSTB_CATAHOMO54-CODSUN =
ZOSVA_CATAHOMO54-CODSUN .
    SELECT SINGLE * FROM T059Z WHERE
LAND1 = 'PE' AND
WITHT = ZOSTB_CATAHOMO54-WITHT AND
WT_WITHCD = ZOSTB_CATAHOMO54-WT_WITHCD .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T059ZT WHERE
LAND1 = T059Z-LAND1 AND
WITHT = T059Z-WITHT AND
WT_WITHCD = T059Z-WT_WITHCD AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO54-TEXT40 =
T059ZT-TEXT40 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_CATAHOMO54-TEXT40 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO54-TEXT40 .
    ENDIF.
    SELECT SINGLE * FROM ZOSTB_CATALOGO54 WHERE
CODSUN = ZOSTB_CATAHOMO54-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO54-DESSUN =
ZOSTB_CATALOGO54-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO54-DESSUN .
    ENDIF.
ENDFORM.
