*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZOSVA_CONSTAKONV................................*
TABLES: ZOSVA_CONSTAKONV, *ZOSVA_CONSTAKONV. "view work areas
CONTROLS: TCTRL_ZOSVA_CONSTAKONV
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZOSVA_CONSTAKONV. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CONSTAKONV.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CONSTAKONV_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTAKONV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTAKONV_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CONSTAKONV_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTAKONV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTAKONV_TOTAL.

*...processing: ZOSVA_CONSTAUART................................*
TABLES: ZOSVA_CONSTAUART, *ZOSVA_CONSTAUART. "view work areas
CONTROLS: TCTRL_ZOSVA_CONSTAUART
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZOSVA_CONSTAUART. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CONSTAUART.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CONSTAUART_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTAUART.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTAUART_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CONSTAUART_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTAUART.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTAUART_TOTAL.

*...processing: ZOSVA_CONSTFKART................................*
TABLES: ZOSVA_CONSTFKART, *ZOSVA_CONSTFKART. "view work areas
CONTROLS: TCTRL_ZOSVA_CONSTFKART
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZOSVA_CONSTFKART. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CONSTFKART.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CONSTFKART_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTFKART.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTFKART_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CONSTFKART_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTFKART.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTFKART_TOTAL.

*...processing: ZOSVA_CONSTKDGRP................................*
TABLES: ZOSVA_CONSTKDGRP, *ZOSVA_CONSTKDGRP. "view work areas
CONTROLS: TCTRL_ZOSVA_CONSTKDGRP
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZOSVA_CONSTKDGRP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CONSTKDGRP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CONSTKDGRP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTKDGRP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTKDGRP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CONSTKDGRP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTKDGRP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTKDGRP_TOTAL.

*...processing: ZOSVA_CONSTPSTYV................................*
TABLES: ZOSVA_CONSTPSTYV, *ZOSVA_CONSTPSTYV. "view work areas
CONTROLS: TCTRL_ZOSVA_CONSTPSTYV
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZOSVA_CONSTPSTYV. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CONSTPSTYV.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CONSTPSTYV_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTPSTYV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTPSTYV_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CONSTPSTYV_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CONSTPSTYV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CONSTPSTYV_TOTAL.

*.........table declarations:.................................*
TABLES: ZOSTB_CONSTAKONV               .
TABLES: ZOSTB_CONSTAUART               .
TABLES: ZOSTB_CONSTFKART               .
TABLES: ZOSTB_CONSTKDGRP               .
TABLES: ZOSTB_CONSTPSTYV               .
