*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZOSFEVA_CATACONS................................*
TABLES: ZOSFEVA_CATACONS, *ZOSFEVA_CATACONS. "view work areas
CONTROLS: TCTRL_ZOSFEVA_CATACONS
TYPE TABLEVIEW USING SCREEN '0900'.
DATA: BEGIN OF STATUS_ZOSFEVA_CATACONS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSFEVA_CATACONS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSFEVA_CATACONS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSFEVA_CATACONS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSFEVA_CATACONS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSFEVA_CATACONS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSFEVA_CATACONS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSFEVA_CATACONS_TOTAL.

*...processing: ZOSVA_CATALOGO01................................*
TABLES: ZOSVA_CATALOGO01, *ZOSVA_CATALOGO01. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO01
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO01. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO01.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO01_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO01.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO01_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO01_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO01.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO01_TOTAL.

*...processing: ZOSVA_CATALOGO03................................*
TABLES: ZOSVA_CATALOGO03, *ZOSVA_CATALOGO03. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO03
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO03. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO03.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO03_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO03.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO03_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO03_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO03.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO03_TOTAL.

*...processing: ZOSVA_CATALOGO05................................*
TABLES: ZOSVA_CATALOGO05, *ZOSVA_CATALOGO05. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO05
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO05. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO05.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO05_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO05.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO05_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO05_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO05.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO05_TOTAL.

*...processing: ZOSVA_CATALOGO06................................*
TABLES: ZOSVA_CATALOGO06, *ZOSVA_CATALOGO06. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO06
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO06. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO06.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO06_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO06.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO06_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO06_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO06.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO06_TOTAL.

*...processing: ZOSVA_CATALOGO07................................*
TABLES: ZOSVA_CATALOGO07, *ZOSVA_CATALOGO07. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO07
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO07. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO07.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO07_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO07.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO07_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO07_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO07.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO07_TOTAL.

*...processing: ZOSVA_CATALOGO11................................*
TABLES: ZOSVA_CATALOGO11, *ZOSVA_CATALOGO11. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO11
TYPE TABLEVIEW USING SCREEN '0011'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO11. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO11.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO11_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO11.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO11_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO11_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO11.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO11_TOTAL.

*...processing: ZOSVA_CATALOGO12................................*
TABLES: ZOSVA_CATALOGO12, *ZOSVA_CATALOGO12. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO12
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO12. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO12.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO12_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO12.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO12_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO12_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO12.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO12_TOTAL.

*...processing: ZOSVA_CATALOGO14................................*
TABLES: ZOSVA_CATALOGO14, *ZOSVA_CATALOGO14. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO14
TYPE TABLEVIEW USING SCREEN '0014'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO14. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO14.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO14_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO14.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO14_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO14_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO14.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO14_TOTAL.

*...processing: ZOSVA_CATALOGO15................................*
TABLES: ZOSVA_CATALOGO15, *ZOSVA_CATALOGO15. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO15
TYPE TABLEVIEW USING SCREEN '0015'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO15. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO15.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO15_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO15.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO15_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO15_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO15.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO15_TOTAL.

*...processing: ZOSVA_CATALOGO16................................*
TABLES: ZOSVA_CATALOGO16, *ZOSVA_CATALOGO16. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO16
TYPE TABLEVIEW USING SCREEN '0016'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO16. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO16.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO16_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO16.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO16_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO16_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO16.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO16_TOTAL.

*...processing: ZOSVA_CATALOGO17................................*
TABLES: ZOSVA_CATALOGO17, *ZOSVA_CATALOGO17. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO17
TYPE TABLEVIEW USING SCREEN '0017'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO17. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO17.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO17_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO17.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO17_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO17_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO17.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO17_TOTAL.

*...processing: ZOSVA_CATALOGO18................................*
TABLES: ZOSVA_CATALOGO18, *ZOSVA_CATALOGO18. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO18
TYPE TABLEVIEW USING SCREEN '0018'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO18. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO18.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO18_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO18.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO18_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO18_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO18.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO18_TOTAL.

*...processing: ZOSVA_CATALOGO20................................*
TABLES: ZOSVA_CATALOGO20, *ZOSVA_CATALOGO20. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO20
TYPE TABLEVIEW USING SCREEN '0020'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO20. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO20.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO20_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO20.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO20_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO20_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO20.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO20_TOTAL.

*...processing: ZOSVA_CATALOGO21................................*
TABLES: ZOSVA_CATALOGO21, *ZOSVA_CATALOGO21. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO21
TYPE TABLEVIEW USING SCREEN '0021'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO21. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO21.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO21_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO21.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO21_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO21_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO21.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO21_TOTAL.

*...processing: ZOSVA_CATALOGO22................................*
TABLES: ZOSVA_CATALOGO22, *ZOSVA_CATALOGO22. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO22
TYPE TABLEVIEW USING SCREEN '0022'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO22. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO22.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO22_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO22.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO22_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO22_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO22.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO22_TOTAL.

*...processing: ZOSVA_CATALOGO23................................*
TABLES: ZOSVA_CATALOGO23, *ZOSVA_CATALOGO23. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO23
TYPE TABLEVIEW USING SCREEN '0023'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO23. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO23.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO23_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO23.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO23_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO23_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO23.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO23_TOTAL.

*...processing: ZOSVA_CATALOGO51................................*
TABLES: ZOSVA_CATALOGO51, *ZOSVA_CATALOGO51. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO51
TYPE TABLEVIEW USING SCREEN '0051'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO51. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO51.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO51_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO51.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO51_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO51_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO51.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO51_TOTAL.

*...processing: ZOSVA_CATALOGO52................................*
TABLES: ZOSVA_CATALOGO52, *ZOSVA_CATALOGO52. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO52
TYPE TABLEVIEW USING SCREEN '0052'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO52. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO52.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO52_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO52.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO52_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO52_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO52.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO52_TOTAL.

*...processing: ZOSVA_CATALOGO53................................*
TABLES: ZOSVA_CATALOGO53, *ZOSVA_CATALOGO53. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO53
TYPE TABLEVIEW USING SCREEN '0053'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO53. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO53.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO53_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO53.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO53_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO53_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO53.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO53_TOTAL.

*...processing: ZOSVA_CATALOGO54................................*
TABLES: ZOSVA_CATALOGO54, *ZOSVA_CATALOGO54. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO54
TYPE TABLEVIEW USING SCREEN '0054'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO54. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO54.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO54_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO54.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO54_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO54_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO54.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO54_TOTAL.

*...processing: ZOSVA_CATALOGO59................................*
TABLES: ZOSVA_CATALOGO59, *ZOSVA_CATALOGO59. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO59
TYPE TABLEVIEW USING SCREEN '0059'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO59. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO59.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO59_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO59.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO59_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO59_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO59.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO59_TOTAL.

*...processing: ZOSVA_CATALOGO61................................*
TABLES: ZOSVA_CATALOGO61, *ZOSVA_CATALOGO61. "view work areas
CONTROLS: TCTRL_ZOSVA_CATALOGO61
TYPE TABLEVIEW USING SCREEN '0061'.
DATA: BEGIN OF STATUS_ZOSVA_CATALOGO61. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATALOGO61.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATALOGO61_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO61.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO61_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATALOGO61_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATALOGO61.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATALOGO61_TOTAL.

*.........table declarations:.................................*
TABLES: T006                           .
TABLES: T006A                          .
TABLES: ZOSFETB_CATACONS               .
TABLES: ZOSTB_CATALOGO01               .
TABLES: ZOSTB_CATALOGO03               .
TABLES: ZOSTB_CATALOGO05               .
TABLES: ZOSTB_CATALOGO06               .
TABLES: ZOSTB_CATALOGO07               .
TABLES: ZOSTB_CATALOGO11               .
TABLES: ZOSTB_CATALOGO12               .
TABLES: ZOSTB_CATALOGO14               .
TABLES: ZOSTB_CATALOGO15               .
TABLES: ZOSTB_CATALOGO16               .
TABLES: ZOSTB_CATALOGO17               .
TABLES: ZOSTB_CATALOGO18               .
TABLES: ZOSTB_CATALOGO20               .
TABLES: ZOSTB_CATALOGO21               .
TABLES: ZOSTB_CATALOGO22               .
TABLES: ZOSTB_CATALOGO23               .
TABLES: ZOSTB_CATALOGO51               .
TABLES: ZOSTB_CATALOGO52               .
TABLES: ZOSTB_CATALOGO53               .
TABLES: ZOSTB_CATALOGO54               .
TABLES: ZOSTB_CATALOGO59               .
TABLES: ZOSTB_CATALOGO61               .
