*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO59................................*
FORM GET_DATA_ZOSVA_CATAHOMO59.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CATAHOMO59 WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CATAHOMO59 .
ZOSVA_CATAHOMO59-MANDT =
ZOSTB_CATAHOMO59-MANDT .
ZOSVA_CATAHOMO59-ZLSCH =
ZOSTB_CATAHOMO59-ZLSCH .
ZOSVA_CATAHOMO59-CODSUN =
ZOSTB_CATAHOMO59-CODSUN .
    SELECT SINGLE * FROM ZOSTB_CATALOGO59 WHERE
CODSUN = ZOSTB_CATAHOMO59-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO59-DESSUN =
ZOSTB_CATALOGO59-DESSUN .
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_CATAHOMO59.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CATAHOMO59 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CATAHOMO59.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CATAHOMO59-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO59 WHERE
  ZLSCH = ZOSVA_CATAHOMO59-ZLSCH .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CATAHOMO59 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CATAHOMO59 WHERE
  ZLSCH = ZOSVA_CATAHOMO59-ZLSCH .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CATAHOMO59.
    ENDIF.
ZOSTB_CATAHOMO59-MANDT =
ZOSVA_CATAHOMO59-MANDT .
ZOSTB_CATAHOMO59-ZLSCH =
ZOSVA_CATAHOMO59-ZLSCH .
ZOSTB_CATAHOMO59-CODSUN =
ZOSVA_CATAHOMO59-CODSUN .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CATAHOMO59 .
    ELSE.
    INSERT ZOSTB_CATAHOMO59 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CATAHOMO59-UPD_FLAG,
STATUS_ZOSVA_CATAHOMO59-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CATAHOMO59.
  SELECT SINGLE * FROM ZOSTB_CATAHOMO59 WHERE
ZLSCH = ZOSVA_CATAHOMO59-ZLSCH .
ZOSVA_CATAHOMO59-MANDT =
ZOSTB_CATAHOMO59-MANDT .
ZOSVA_CATAHOMO59-ZLSCH =
ZOSTB_CATAHOMO59-ZLSCH .
ZOSVA_CATAHOMO59-CODSUN =
ZOSTB_CATAHOMO59-CODSUN .
    SELECT SINGLE * FROM ZOSTB_CATALOGO59 WHERE
CODSUN = ZOSTB_CATAHOMO59-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO59-DESSUN =
ZOSTB_CATALOGO59-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO59-DESSUN .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CATAHOMO59 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CATAHOMO59-ZLSCH TO
ZOSTB_CATAHOMO59-ZLSCH .
MOVE ZOSVA_CATAHOMO59-MANDT TO
ZOSTB_CATAHOMO59-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CATAHOMO59'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CATAHOMO59 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CATAHOMO59'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_CATAHOMO59 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_CATAHOMO59-MANDT =
ZOSVA_CATAHOMO59-MANDT .
ZOSTB_CATAHOMO59-ZLSCH =
ZOSVA_CATAHOMO59-ZLSCH .
ZOSTB_CATAHOMO59-CODSUN =
ZOSVA_CATAHOMO59-CODSUN .
    SELECT SINGLE * FROM ZOSTB_CATALOGO59 WHERE
CODSUN = ZOSTB_CATAHOMO59-CODSUN .
    IF SY-SUBRC EQ 0.
ZOSVA_CATAHOMO59-DESSUN =
ZOSTB_CATALOGO59-DESSUN .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_CATAHOMO59-DESSUN .
    ENDIF.
ENDFORM.
