*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZOSVA_CATAHOMO03................................*
TABLES: ZOSVA_CATAHOMO03, *ZOSVA_CATAHOMO03. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO03
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO03. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO03.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO03_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO03.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO03_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO03_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO03.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO03_TOTAL.

*...processing: ZOSVA_CATAHOMO06................................*
TABLES: ZOSVA_CATAHOMO06, *ZOSVA_CATAHOMO06. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO06
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO06. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO06.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO06_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO06.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO06_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO06_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO06.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO06_TOTAL.

*...processing: ZOSVA_CATAHOMO07................................*
TABLES: ZOSVA_CATAHOMO07, *ZOSVA_CATAHOMO07. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO07
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO07. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO07.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO07_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO07.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO07_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO07_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO07.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO07_TOTAL.

*...processing: ZOSVA_CATAHOMO08................................*
TABLES: ZOSVA_CATAHOMO08, *ZOSVA_CATAHOMO08. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO08
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO08. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO08.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO08_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO08.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO08_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO08_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO08.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO08_TOTAL.

*...processing: ZOSVA_CATAHOMO09................................*
TABLES: ZOSVA_CATAHOMO09, *ZOSVA_CATAHOMO09. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO09
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO09. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO09.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO09_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO09.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO09_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO09_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO09.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO09_TOTAL.

*...processing: ZOSVA_CATAHOMO10................................*
TABLES: ZOSVA_CATAHOMO10, *ZOSVA_CATAHOMO10. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO10
TYPE TABLEVIEW USING SCREEN '0010'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO10. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO10.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO10_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO10.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO10_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO10_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO10.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO10_TOTAL.

*...processing: ZOSVA_CATAHOMO12................................*
TABLES: ZOSVA_CATAHOMO12, *ZOSVA_CATAHOMO12. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO12
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO12. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO12.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO12_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO12.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO12_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO12_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO12.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO12_TOTAL.

*...processing: ZOSVA_CATAHOMO15................................*
TABLES: ZOSVA_CATAHOMO15, *ZOSVA_CATAHOMO15. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO15
TYPE TABLEVIEW USING SCREEN '0015'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO15. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO15.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO15_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO15.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO15_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO15_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO15.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO15_TOTAL.

*...processing: ZOSVA_CATAHOMO18................................*
TABLES: ZOSVA_CATAHOMO18, *ZOSVA_CATAHOMO18. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO18
TYPE TABLEVIEW USING SCREEN '0018'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO18. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO18.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO18_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO18.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO18_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO18_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO18.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO18_TOTAL.

*...processing: ZOSVA_CATAHOMO20................................*
TABLES: ZOSVA_CATAHOMO20, *ZOSVA_CATAHOMO20. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO20
TYPE TABLEVIEW USING SCREEN '0020'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO20. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO20.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO20_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO20.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO20_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO20_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO20.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO20_TOTAL.

*...processing: ZOSVA_CATAHOMO22................................*
TABLES: ZOSVA_CATAHOMO22, *ZOSVA_CATAHOMO22. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO22
TYPE TABLEVIEW USING SCREEN '0022'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO22. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO22.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO22_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO22.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO22_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO22_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO22.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO22_TOTAL.

*...processing: ZOSVA_CATAHOMO23................................*
TABLES: ZOSVA_CATAHOMO23, *ZOSVA_CATAHOMO23. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO23
TYPE TABLEVIEW USING SCREEN '0023'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO23. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO23.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO23_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO23.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO23_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO23_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO23.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO23_TOTAL.

*...processing: ZOSVA_CATAHOMO51................................*
TABLES: ZOSVA_CATAHOMO51, *ZOSVA_CATAHOMO51. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO51
TYPE TABLEVIEW USING SCREEN '0051'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO51. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO51.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO51_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO51.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO51_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO51_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO51.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO51_TOTAL.

*...processing: ZOSVA_CATAHOMO53................................*
TABLES: ZOSVA_CATAHOMO53, *ZOSVA_CATAHOMO53. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO53
TYPE TABLEVIEW USING SCREEN '0053'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO53. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO53.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO53_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO53.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO53_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO53_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO53.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO53_TOTAL.

*...processing: ZOSVA_CATAHOMO54................................*
TABLES: ZOSVA_CATAHOMO54, *ZOSVA_CATAHOMO54. "view work areas
CONTROLS: TCTRL_ZOSVA_CATAHOMO54
TYPE TABLEVIEW USING SCREEN '0054'.
DATA: BEGIN OF STATUS_ZOSVA_CATAHOMO54. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZOSVA_CATAHOMO54.
* Table for entries selected to show on screen
DATA: BEGIN OF ZOSVA_CATAHOMO54_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO54.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO54_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZOSVA_CATAHOMO54_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZOSVA_CATAHOMO54.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZOSVA_CATAHOMO54_TOTAL.

*.........table declarations:.................................*
TABLES: T006                           .
TABLES: T006A                          .
TABLES: T059Z                          .
TABLES: T059ZT                         .
TABLES: ZOSTB_CATAHOMO03               .
TABLES: ZOSTB_CATAHOMO06               .
TABLES: ZOSTB_CATAHOMO07               .
TABLES: ZOSTB_CATAHOMO08               .
TABLES: ZOSTB_CATAHOMO09               .
TABLES: ZOSTB_CATAHOMO10               .
TABLES: ZOSTB_CATAHOMO12               .
TABLES: ZOSTB_CATAHOMO15               .
TABLES: ZOSTB_CATAHOMO18               .
TABLES: ZOSTB_CATAHOMO20               .
TABLES: ZOSTB_CATAHOMO22               .
TABLES: ZOSTB_CATAHOMO23               .
TABLES: ZOSTB_CATAHOMO51               .
TABLES: ZOSTB_CATAHOMO53               .
TABLES: ZOSTB_CATAHOMO54               .
TABLES: ZOSTB_CATALOGO20               .
TABLES: ZOSTB_CATALOGO22               .
TABLES: ZOSTB_CATALOGO23               .
TABLES: ZOSTB_CATALOGO51               .
TABLES: ZOSTB_CATALOGO53               .
TABLES: ZOSTB_CATALOGO54               .
