*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_T003_I....................................*
FORM GET_DATA_ZOSVA_T003_I.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_T003_I WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_T003_I .
ZOSVA_T003_I-MANDT =
ZOSTB_T003_I-MANDT .
ZOSVA_T003_I-LAND1 =
ZOSTB_T003_I-LAND1 .
ZOSVA_T003_I-FKART =
ZOSTB_T003_I-FKART .
ZOSVA_T003_I-DOCCLS =
ZOSTB_T003_I-DOCCLS .
    SELECT SINGLE * FROM T005 WHERE
LAND1 = ZOSTB_T003_I-LAND1 .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T005T WHERE
LAND1 = T005-LAND1 AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-LANDX =
T005T-LANDX .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM TVFK WHERE
FKART = ZOSTB_T003_I-FKART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TVFKT WHERE
FKART = TVFK-FKART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-VTEXT =
TVFKT-VTEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM DOCCLSS WHERE
LAND1 = ZOSTB_T003_I-LAND1 AND
DOCCLS = ZOSTB_T003_I-DOCCLS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM DOCCLSST WHERE
LAND1 = DOCCLSS-LAND1 AND
DOCCLS = DOCCLSS-DOCCLS AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-TEXT30 =
DOCCLSST-TEXT30 .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZOSVA_T003_I.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_T003_I .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_T003_I.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_T003_I-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_T003_I WHERE
  LAND1 = ZOSVA_T003_I-LAND1 AND
  FKART = ZOSVA_T003_I-FKART .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_T003_I .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_T003_I WHERE
  LAND1 = ZOSVA_T003_I-LAND1 AND
  FKART = ZOSVA_T003_I-FKART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_T003_I.
    ENDIF.
ZOSTB_T003_I-MANDT =
ZOSVA_T003_I-MANDT .
ZOSTB_T003_I-LAND1 =
ZOSVA_T003_I-LAND1 .
ZOSTB_T003_I-FKART =
ZOSVA_T003_I-FKART .
ZOSTB_T003_I-DOCCLS =
ZOSVA_T003_I-DOCCLS .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_T003_I .
    ELSE.
    INSERT ZOSTB_T003_I .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_T003_I-UPD_FLAG,
STATUS_ZOSVA_T003_I-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_T003_I.
  SELECT SINGLE * FROM ZOSTB_T003_I WHERE
LAND1 = ZOSVA_T003_I-LAND1 AND
FKART = ZOSVA_T003_I-FKART .
ZOSVA_T003_I-MANDT =
ZOSTB_T003_I-MANDT .
ZOSVA_T003_I-LAND1 =
ZOSTB_T003_I-LAND1 .
ZOSVA_T003_I-FKART =
ZOSTB_T003_I-FKART .
ZOSVA_T003_I-DOCCLS =
ZOSTB_T003_I-DOCCLS .
    SELECT SINGLE * FROM T005 WHERE
LAND1 = ZOSTB_T003_I-LAND1 .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T005T WHERE
LAND1 = T005-LAND1 AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-LANDX =
T005T-LANDX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_T003_I-LANDX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_T003_I-LANDX .
    ENDIF.
    SELECT SINGLE * FROM TVFK WHERE
FKART = ZOSTB_T003_I-FKART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TVFKT WHERE
FKART = TVFK-FKART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-VTEXT =
TVFKT-VTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_T003_I-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_T003_I-VTEXT .
    ENDIF.
    SELECT SINGLE * FROM DOCCLSS WHERE
LAND1 = ZOSTB_T003_I-LAND1 AND
DOCCLS = ZOSTB_T003_I-DOCCLS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM DOCCLSST WHERE
LAND1 = DOCCLSS-LAND1 AND
DOCCLS = DOCCLSS-DOCCLS AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-TEXT30 =
DOCCLSST-TEXT30 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_T003_I-TEXT30 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_T003_I-TEXT30 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_T003_I USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_T003_I-LAND1 TO
ZOSTB_T003_I-LAND1 .
MOVE ZOSVA_T003_I-FKART TO
ZOSTB_T003_I-FKART .
MOVE ZOSVA_T003_I-MANDT TO
ZOSTB_T003_I-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_T003_I'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_T003_I TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_T003_I'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZOSVA_T003_I USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZOSTB_T003_I-MANDT =
ZOSVA_T003_I-MANDT .
ZOSTB_T003_I-LAND1 =
ZOSVA_T003_I-LAND1 .
ZOSTB_T003_I-FKART =
ZOSVA_T003_I-FKART .
ZOSTB_T003_I-DOCCLS =
ZOSVA_T003_I-DOCCLS .
    SELECT SINGLE * FROM T005 WHERE
LAND1 = ZOSTB_T003_I-LAND1 .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T005T WHERE
LAND1 = T005-LAND1 AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-LANDX =
T005T-LANDX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_T003_I-LANDX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_T003_I-LANDX .
    ENDIF.
    SELECT SINGLE * FROM TVFK WHERE
FKART = ZOSTB_T003_I-FKART .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TVFKT WHERE
FKART = TVFK-FKART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-VTEXT =
TVFKT-VTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_T003_I-VTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_T003_I-VTEXT .
    ENDIF.
    SELECT SINGLE * FROM DOCCLSS WHERE
LAND1 = ZOSTB_T003_I-LAND1 AND
DOCCLS = ZOSTB_T003_I-DOCCLS .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM DOCCLSST WHERE
LAND1 = DOCCLSS-LAND1 AND
DOCCLS = DOCCLSS-DOCCLS AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZOSVA_T003_I-TEXT30 =
DOCCLSST-TEXT30 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZOSVA_T003_I-TEXT30 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZOSVA_T003_I-TEXT30 .
    ENDIF.
ENDFORM.
