*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_MATEXON...................................*
FORM GET_DATA_ZOSVA_MATEXON.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_MATEXON WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_MATEXON .
ZOSVA_MATEXON-MANDT =
ZOSTB_MATEXON-MANDT .
ZOSVA_MATEXON-VKORG =
ZOSTB_MATEXON-VKORG .
ZOSVA_MATEXON-VTWEG =
ZOSTB_MATEXON-VTWEG .
ZOSVA_MATEXON-MATNR =
ZOSTB_MATEXON-MATNR .
ZOSVA_MATEXON-DATAB =
ZOSTB_MATEXON-DATAB .
ZOSVA_MATEXON-DATBI =
ZOSTB_MATEXON-DATBI .
ZOSVA_MATEXON-ERNAM =
ZOSTB_MATEXON-ERNAM .
ZOSVA_MATEXON-ERDAT =
ZOSTB_MATEXON-ERDAT .
ZOSVA_MATEXON-ERZET =
ZOSTB_MATEXON-ERZET .
<VIM_TOTAL_STRUC> = ZOSVA_MATEXON.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_MATEXON .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_MATEXON.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_MATEXON-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_MATEXON WHERE
  VKORG = ZOSVA_MATEXON-VKORG AND
  VTWEG = ZOSVA_MATEXON-VTWEG AND
  MATNR = ZOSVA_MATEXON-MATNR AND
  DATAB = ZOSVA_MATEXON-DATAB .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_MATEXON .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_MATEXON WHERE
  VKORG = ZOSVA_MATEXON-VKORG AND
  VTWEG = ZOSVA_MATEXON-VTWEG AND
  MATNR = ZOSVA_MATEXON-MATNR AND
  DATAB = ZOSVA_MATEXON-DATAB .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_MATEXON.
    ENDIF.
ZOSTB_MATEXON-MANDT =
ZOSVA_MATEXON-MANDT .
ZOSTB_MATEXON-VKORG =
ZOSVA_MATEXON-VKORG .
ZOSTB_MATEXON-VTWEG =
ZOSVA_MATEXON-VTWEG .
ZOSTB_MATEXON-MATNR =
ZOSVA_MATEXON-MATNR .
ZOSTB_MATEXON-DATAB =
ZOSVA_MATEXON-DATAB .
ZOSTB_MATEXON-DATBI =
ZOSVA_MATEXON-DATBI .
ZOSTB_MATEXON-ERNAM =
ZOSVA_MATEXON-ERNAM .
ZOSTB_MATEXON-ERDAT =
ZOSVA_MATEXON-ERDAT .
ZOSTB_MATEXON-ERZET =
ZOSVA_MATEXON-ERZET .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_MATEXON .
    ELSE.
    INSERT ZOSTB_MATEXON .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_MATEXON-UPD_FLAG,
STATUS_ZOSVA_MATEXON-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_MATEXON.
  SELECT SINGLE * FROM ZOSTB_MATEXON WHERE
VKORG = ZOSVA_MATEXON-VKORG AND
VTWEG = ZOSVA_MATEXON-VTWEG AND
MATNR = ZOSVA_MATEXON-MATNR AND
DATAB = ZOSVA_MATEXON-DATAB .
ZOSVA_MATEXON-MANDT =
ZOSTB_MATEXON-MANDT .
ZOSVA_MATEXON-VKORG =
ZOSTB_MATEXON-VKORG .
ZOSVA_MATEXON-VTWEG =
ZOSTB_MATEXON-VTWEG .
ZOSVA_MATEXON-MATNR =
ZOSTB_MATEXON-MATNR .
ZOSVA_MATEXON-DATAB =
ZOSTB_MATEXON-DATAB .
ZOSVA_MATEXON-DATBI =
ZOSTB_MATEXON-DATBI .
ZOSVA_MATEXON-ERNAM =
ZOSTB_MATEXON-ERNAM .
ZOSVA_MATEXON-ERDAT =
ZOSTB_MATEXON-ERDAT .
ZOSVA_MATEXON-ERZET =
ZOSTB_MATEXON-ERZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_MATEXON USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_MATEXON-VKORG TO
ZOSTB_MATEXON-VKORG .
MOVE ZOSVA_MATEXON-VTWEG TO
ZOSTB_MATEXON-VTWEG .
MOVE ZOSVA_MATEXON-MATNR TO
ZOSTB_MATEXON-MATNR .
MOVE ZOSVA_MATEXON-DATAB TO
ZOSTB_MATEXON-DATAB .
MOVE ZOSVA_MATEXON-MANDT TO
ZOSTB_MATEXON-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_MATEXON'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_MATEXON TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_MATEXON'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
