*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSFEVA_ASGCODES................................*
FORM GET_DATA_ZOSFEVA_ASGCODES.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSFETB_ASGCODES WHERE
(VIM_WHERETAB) .
    CLEAR ZOSFEVA_ASGCODES .
ZOSFEVA_ASGCODES-MANDT =
ZOSFETB_ASGCODES-MANDT .
ZOSFEVA_ASGCODES-WERKS =
ZOSFETB_ASGCODES-WERKS .
ZOSFEVA_ASGCODES-ZZ_CODIGO_SUNAT =
ZOSFETB_ASGCODES-ZZ_CODIGO_SUNAT .
ZOSFEVA_ASGCODES-ZZ_DESC_COD_SUNA =
ZOSFETB_ASGCODES-ZZ_DESC_COD_SUNA .
<VIM_TOTAL_STRUC> = ZOSFEVA_ASGCODES.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSFEVA_ASGCODES .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSFEVA_ASGCODES.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSFEVA_ASGCODES-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSFETB_ASGCODES WHERE
  WERKS = ZOSFEVA_ASGCODES-WERKS .
    IF SY-SUBRC = 0.
    DELETE ZOSFETB_ASGCODES .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSFETB_ASGCODES WHERE
  WERKS = ZOSFEVA_ASGCODES-WERKS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSFETB_ASGCODES.
    ENDIF.
ZOSFETB_ASGCODES-MANDT =
ZOSFEVA_ASGCODES-MANDT .
ZOSFETB_ASGCODES-WERKS =
ZOSFEVA_ASGCODES-WERKS .
ZOSFETB_ASGCODES-ZZ_CODIGO_SUNAT =
ZOSFEVA_ASGCODES-ZZ_CODIGO_SUNAT .
ZOSFETB_ASGCODES-ZZ_DESC_COD_SUNA =
ZOSFEVA_ASGCODES-ZZ_DESC_COD_SUNA .
    IF SY-SUBRC = 0.
    UPDATE ZOSFETB_ASGCODES .
    ELSE.
    INSERT ZOSFETB_ASGCODES .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSFEVA_ASGCODES-UPD_FLAG,
STATUS_ZOSFEVA_ASGCODES-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSFEVA_ASGCODES.
  SELECT SINGLE * FROM ZOSFETB_ASGCODES WHERE
WERKS = ZOSFEVA_ASGCODES-WERKS .
ZOSFEVA_ASGCODES-MANDT =
ZOSFETB_ASGCODES-MANDT .
ZOSFEVA_ASGCODES-WERKS =
ZOSFETB_ASGCODES-WERKS .
ZOSFEVA_ASGCODES-ZZ_CODIGO_SUNAT =
ZOSFETB_ASGCODES-ZZ_CODIGO_SUNAT .
ZOSFEVA_ASGCODES-ZZ_DESC_COD_SUNA =
ZOSFETB_ASGCODES-ZZ_DESC_COD_SUNA .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSFEVA_ASGCODES USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSFEVA_ASGCODES-WERKS TO
ZOSFETB_ASGCODES-WERKS .
MOVE ZOSFEVA_ASGCODES-MANDT TO
ZOSFETB_ASGCODES-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSFETB_ASGCODES'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSFETB_ASGCODES TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSFETB_ASGCODES'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
