*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_LOTNO.....................................*
FORM GET_DATA_ZOSVA_LOTNO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_LOTNO WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_LOTNO .
ZOSVA_LOTNO-MANDT =
ZOSTB_LOTNO-MANDT .
ZOSVA_LOTNO-LOTNO =
ZOSTB_LOTNO-LOTNO .
ZOSVA_LOTNO-IS_LOTNO_GR =
ZOSTB_LOTNO-IS_LOTNO_GR .
<VIM_TOTAL_STRUC> = ZOSVA_LOTNO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_LOTNO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_LOTNO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_LOTNO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_LOTNO WHERE
  LOTNO = ZOSVA_LOTNO-LOTNO .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_LOTNO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_LOTNO WHERE
  LOTNO = ZOSVA_LOTNO-LOTNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_LOTNO.
    ENDIF.
ZOSTB_LOTNO-MANDT =
ZOSVA_LOTNO-MANDT .
ZOSTB_LOTNO-LOTNO =
ZOSVA_LOTNO-LOTNO .
ZOSTB_LOTNO-IS_LOTNO_GR =
ZOSVA_LOTNO-IS_LOTNO_GR .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_LOTNO .
    ELSE.
    INSERT ZOSTB_LOTNO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_LOTNO-UPD_FLAG,
STATUS_ZOSVA_LOTNO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_LOTNO.
  SELECT SINGLE * FROM ZOSTB_LOTNO WHERE
LOTNO = ZOSVA_LOTNO-LOTNO .
ZOSVA_LOTNO-MANDT =
ZOSTB_LOTNO-MANDT .
ZOSVA_LOTNO-LOTNO =
ZOSTB_LOTNO-LOTNO .
ZOSVA_LOTNO-IS_LOTNO_GR =
ZOSTB_LOTNO-IS_LOTNO_GR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_LOTNO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_LOTNO-LOTNO TO
ZOSTB_LOTNO-LOTNO .
MOVE ZOSVA_LOTNO-MANDT TO
ZOSTB_LOTNO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_LOTNO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_LOTNO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_LOTNO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
