*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZOSVA_CONST_FE..................................*
FORM GET_DATA_ZOSVA_CONST_FE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOSTB_CONST_FE WHERE
(VIM_WHERETAB) .
    CLEAR ZOSVA_CONST_FE .
ZOSVA_CONST_FE-MANDT =
ZOSTB_CONST_FE-MANDT .
ZOSVA_CONST_FE-MODULO =
ZOSTB_CONST_FE-MODULO .
ZOSVA_CONST_FE-APLICACION =
ZOSTB_CONST_FE-APLICACION .
ZOSVA_CONST_FE-PROGRAMA =
ZOSTB_CONST_FE-PROGRAMA .
ZOSVA_CONST_FE-CAMPO =
ZOSTB_CONST_FE-CAMPO .
ZOSVA_CONST_FE-SECUENCIA =
ZOSTB_CONST_FE-SECUENCIA .
ZOSVA_CONST_FE-SIGNO =
ZOSTB_CONST_FE-SIGNO .
ZOSVA_CONST_FE-OPCION =
ZOSTB_CONST_FE-OPCION .
ZOSVA_CONST_FE-VALOR1 =
ZOSTB_CONST_FE-VALOR1 .
ZOSVA_CONST_FE-VALOR2 =
ZOSTB_CONST_FE-VALOR2 .
ZOSVA_CONST_FE-DESCRIP =
ZOSTB_CONST_FE-DESCRIP .
ZOSVA_CONST_FE-UNAME =
ZOSTB_CONST_FE-UNAME .
ZOSVA_CONST_FE-DATUM =
ZOSTB_CONST_FE-DATUM .
ZOSVA_CONST_FE-UZEIT =
ZOSTB_CONST_FE-UZEIT .
<VIM_TOTAL_STRUC> = ZOSVA_CONST_FE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOSVA_CONST_FE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOSVA_CONST_FE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOSVA_CONST_FE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CONST_FE WHERE
  MODULO = ZOSVA_CONST_FE-MODULO AND
  APLICACION = ZOSVA_CONST_FE-APLICACION AND
  PROGRAMA = ZOSVA_CONST_FE-PROGRAMA AND
  CAMPO = ZOSVA_CONST_FE-CAMPO AND
  SECUENCIA = ZOSVA_CONST_FE-SECUENCIA .
    IF SY-SUBRC = 0.
    DELETE ZOSTB_CONST_FE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOSTB_CONST_FE WHERE
  MODULO = ZOSVA_CONST_FE-MODULO AND
  APLICACION = ZOSVA_CONST_FE-APLICACION AND
  PROGRAMA = ZOSVA_CONST_FE-PROGRAMA AND
  CAMPO = ZOSVA_CONST_FE-CAMPO AND
  SECUENCIA = ZOSVA_CONST_FE-SECUENCIA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOSTB_CONST_FE.
    ENDIF.
ZOSTB_CONST_FE-MANDT =
ZOSVA_CONST_FE-MANDT .
ZOSTB_CONST_FE-MODULO =
ZOSVA_CONST_FE-MODULO .
ZOSTB_CONST_FE-APLICACION =
ZOSVA_CONST_FE-APLICACION .
ZOSTB_CONST_FE-PROGRAMA =
ZOSVA_CONST_FE-PROGRAMA .
ZOSTB_CONST_FE-CAMPO =
ZOSVA_CONST_FE-CAMPO .
ZOSTB_CONST_FE-SECUENCIA =
ZOSVA_CONST_FE-SECUENCIA .
ZOSTB_CONST_FE-SIGNO =
ZOSVA_CONST_FE-SIGNO .
ZOSTB_CONST_FE-OPCION =
ZOSVA_CONST_FE-OPCION .
ZOSTB_CONST_FE-VALOR1 =
ZOSVA_CONST_FE-VALOR1 .
ZOSTB_CONST_FE-VALOR2 =
ZOSVA_CONST_FE-VALOR2 .
ZOSTB_CONST_FE-DESCRIP =
ZOSVA_CONST_FE-DESCRIP .
ZOSTB_CONST_FE-UNAME =
ZOSVA_CONST_FE-UNAME .
ZOSTB_CONST_FE-DATUM =
ZOSVA_CONST_FE-DATUM .
ZOSTB_CONST_FE-UZEIT =
ZOSVA_CONST_FE-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE ZOSTB_CONST_FE .
    ELSE.
    INSERT ZOSTB_CONST_FE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOSVA_CONST_FE-UPD_FLAG,
STATUS_ZOSVA_CONST_FE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOSVA_CONST_FE.
  SELECT SINGLE * FROM ZOSTB_CONST_FE WHERE
MODULO = ZOSVA_CONST_FE-MODULO AND
APLICACION = ZOSVA_CONST_FE-APLICACION AND
PROGRAMA = ZOSVA_CONST_FE-PROGRAMA AND
CAMPO = ZOSVA_CONST_FE-CAMPO AND
SECUENCIA = ZOSVA_CONST_FE-SECUENCIA .
ZOSVA_CONST_FE-MANDT =
ZOSTB_CONST_FE-MANDT .
ZOSVA_CONST_FE-MODULO =
ZOSTB_CONST_FE-MODULO .
ZOSVA_CONST_FE-APLICACION =
ZOSTB_CONST_FE-APLICACION .
ZOSVA_CONST_FE-PROGRAMA =
ZOSTB_CONST_FE-PROGRAMA .
ZOSVA_CONST_FE-CAMPO =
ZOSTB_CONST_FE-CAMPO .
ZOSVA_CONST_FE-SECUENCIA =
ZOSTB_CONST_FE-SECUENCIA .
ZOSVA_CONST_FE-SIGNO =
ZOSTB_CONST_FE-SIGNO .
ZOSVA_CONST_FE-OPCION =
ZOSTB_CONST_FE-OPCION .
ZOSVA_CONST_FE-VALOR1 =
ZOSTB_CONST_FE-VALOR1 .
ZOSVA_CONST_FE-VALOR2 =
ZOSTB_CONST_FE-VALOR2 .
ZOSVA_CONST_FE-DESCRIP =
ZOSTB_CONST_FE-DESCRIP .
ZOSVA_CONST_FE-UNAME =
ZOSTB_CONST_FE-UNAME .
ZOSVA_CONST_FE-DATUM =
ZOSTB_CONST_FE-DATUM .
ZOSVA_CONST_FE-UZEIT =
ZOSTB_CONST_FE-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOSVA_CONST_FE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOSVA_CONST_FE-MODULO TO
ZOSTB_CONST_FE-MODULO .
MOVE ZOSVA_CONST_FE-APLICACION TO
ZOSTB_CONST_FE-APLICACION .
MOVE ZOSVA_CONST_FE-PROGRAMA TO
ZOSTB_CONST_FE-PROGRAMA .
MOVE ZOSVA_CONST_FE-CAMPO TO
ZOSTB_CONST_FE-CAMPO .
MOVE ZOSVA_CONST_FE-SECUENCIA TO
ZOSTB_CONST_FE-SECUENCIA .
MOVE ZOSVA_CONST_FE-MANDT TO
ZOSTB_CONST_FE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOSTB_CONST_FE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOSTB_CONST_FE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOSTB_CONST_FE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
